### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by DutchPete** [guopenghui/obsidian-quiet-outline#1]
I installed the plug-in and enabled it, and reloaded Obsidian. This is a header in the main text of a note:

![image](https://user-images.githubusercontent.com/10794265/158841859-feb5cbf1-eb76-44ff-95f2-edfd3a5d758f.png)

and this is the same header in the Outline:

![image](https://user-images.githubusercontent.com/10794265/158841998-1f442042-2854-40c2-8a97-c25b94b07e8c.png)

Using markdown (e.g. `**text**`) is also rendered with asterisks in the Outline.

**Comment by guopenghui** [comment]
Please open "Render Markdown" option in setting panel. It is closed by default.
![image](https://user-images.githubusercontent.com/13451866/158918597-d838197e-98e0-4acd-ae4c-8aae6f6260ed.png)

And it will work fine like: 
![image](https://user-images.githubusercontent.com/13451866/158918715-f2ea7a78-2d84-487b-9f90-635be6ee5fef.png)

**Comment by DutchPete** [comment]
I had already done that. I just now tried it in the Help vault too, but it does not work.
That is odd because it works at your end. Hmmm ……

**Comment by DutchPete** [comment]
Still does not work. I will uninstall it now.

**Comment by guopenghui** [comment]
It's surely strange... When you enable markdown-render option, it should use a different function which renders text to html object but not the text itself.
I'm not sure about the reason. Maybe you can try the latest version from plugin store, or give it up. 😞

**Comment by DutchPete** [comment]
I reinstalled it from the plug-in store, but still could not get it to work, so I'll give it up.
