### ISSUE TITLE
headings collapse when adding new heading

### ISSUE THREAD

**Issue by qiaoxingxing** [guopenghui/obsidian-quiet-outline#101]
When I add a new heading, all the headings will collapase to h1, how to avoid this?

my settings:
- Default Level: H4
- Hide Unsearched: false
- Auto Expand: false

**Comment by skaviouz** [comment]
I too have experienced a similar issue. I have just downloaded this plugin. The only setting I have changed was to change Default Level: H5.

Just like OP said, this is a bug:
- If I create a child header (h4) for a header (h3) that does not have already existing child elements, this plugin acts as that h3 was already collapsed, regardless of the settings.

However, I also found when it didn't bug out:
- When I create new child headers (h3) for header (h2) that has exiting children headers and is also expanded, it will add the new Header to the TOC and you can see it, as one would expect it should.
- If I create a child header for a header that is not expanded (specifically collapsed), the TOC remains collapsed, as one would expect it should.

Personally, I think you should have "previously childless headers" expanded when new new child headers are added to them while the TOC respects specifically collapsed headers or when new child header is greater than the specified maximum "Expand Level" UI's specification.

**Comment by guopenghui** [comment]
Check `0.3.26`. Follow-up discussion moved to #159
