### ISSUE TITLE
标题中的序号不显示

### ISSUE THREAD

**Issue by Holdon-d** [guopenghui/obsidian-quiet-outline#11]
在标题中如果存在“1. xx”的话，只会显示 xx，如图所示，不开 render 的话可以显示，但是带网址的就很难看了。请问能否解决？
![Snipaste_2022-04-02_10-52-06](https://user-images.githubusercontent.com/55305643/161363054-e8c9b7ca-0b4a-43d1-bd2a-bd20c2c4228e.png)

**Comment by guopenghui** [comment]
原因可以看一下readme里面的limitations第二条。
不过这个问题应该还挺烦人的，我尝试修复一下吧，主要是要修改原有的markdown解析规则

**Comment by guopenghui** [comment]
可以实现，下个版本发布。
还有没有其他解析不太合理的地方？

**Comment by Holdon-d** [comment]
大佬牛逼。还有一个不知道算不算，我用的 blue topaz 主题配合本地字体，但是标题是默认字体，设置如下：
![字体设置](https://user-images.githubusercontent.com/55305643/161365428-bf3e901d-8586-4ab4-861b-c562a0ff239a.png)
但是如果标题带了网址，那么在插件里字体显示就会不一样
![大纲](https://user-images.githubusercontent.com/55305643/161365487-84512602-c590-4aa4-a6d9-3bcf8f5be0e7.png)

**Comment by guopenghui** [comment]
这些是CSS设置的效果。
+ 带网址的标题，里面的网址(外链)部分被渲染成了`<a>`元素，所以和编辑器里面的链接一样，会被显示成同样的样式(蓝色、带下划线)
+ 插件内的标题和编辑器内的标题样式不一样，是因为控制编辑器内样式的那个CSS只作用于编辑器：
![image](https://user-images.githubusercontent.com/13451866/161366148-ebe4e3b3-e66d-42db-8f80-dc44ff8dc304.png)
如果想设置成一样的，可以在插件的`styles.css`里面写一个`.quiet-outline h1`规则，然后把其他内容抄进去，比如
![image](https://user-images.githubusercontent.com/13451866/161366339-7a9de905-62f9-4815-8a83-c2e1d6930b6d.png)
这样就有同款的样式了：
![image](https://user-images.githubusercontent.com/13451866/161366353-76a40612-84b8-4511-80c3-bb9c953dabe6.png)

**Comment by Holdon-d** [comment]
明白，多谢大佬

**Comment by guopenghui** [comment]
`0.2.2`里面修正了，可以用`1. xxx`了
