### ISSUE TITLE
有固定展开全部标题这个选项吗

### ISSUE THREAD

**Issue by EvethingIsOK** [guopenghui/obsidian-quiet-outline#110]
不知道是否有固定展开全部标题的选项,不知道是我没找到还是没有这个功能.我想要在正文中上下滑动时候.大纲的标题是一直展开的状态.

**Comment by gradyhandle** [comment]
![image](https://user-images.githubusercontent.com/97155298/231403882-cd11aaa8-90a6-48fe-b2b7-c4744bd1c684.png)
调到h5够用了

**Comment by PYCHBI** [comment]
试试把 “自动展开”一项关闭，然后把展开层级设为H5，这样就保证展开了不会变了

**Comment by guopenghui** [comment]
如上所言，关闭自动展开，然后默认展开层级为最大，就是默认全部展开了

**Comment by EvethingIsOK** [comment]
> 试试把 “自动展开”一项关闭，然后把展开层级设为H5，这样就保证展开了不会变了

解决了 谢谢
