### ISSUE TITLE
页面抖动问题

### ISSUE THREAD

**Issue by Dyse-Sofqi** [guopenghui/obsidian-quiet-outline#113]
点击三次同一目录章节，第一次点击能正常跳转该章节，第二次点击，大纲里该章节底色会变成白色，第三次点击整个页面都会抖动一下，就是整体页面向上跳一行文字的距离

Uploading 1681541014890.mp4…

，闪了一下就恢复了，然后章节白底也恢复正常，不知道是什么问题

**Comment by guopenghui** [comment]
视频没传上来

**Comment by Twenru-zzh** [comment]
我今天刚使用也发现了这个问题，我试了下是和某个插件冲突，但是没找到具体那个

**Comment by Twenru-zzh** [comment]
@Dyse-Sofqi 和Table Enhancer这个插件冲突，我排查过了，但是该插件没有还不在插件市场
