### ISSUE TITLE
大纲滚动定位有点问题

### ISSUE THREAD

**Issue by Erimus-Koo** [guopenghui/obsidian-quiet-outline#114]
在文章的大纲较长（行数多）的情况下，如下配置时，滚动页面内容时，大纲无法跟随滚动到响应位置。感觉它滚了，但没滚到位。

<img width="775" alt="image" src="https://user-images.githubusercontent.com/17139670/232201020-9ebcc30e-2534-4111-ad3c-88b463101156.png">

**Comment by guopenghui** [comment]
滚动用的是 scrollIntoView 方法，应该只能保证滚动到能看见的地方，不保证一定能滚动到中间
