### ISSUE TITLE
面板仅在右侧打开

### ISSUE THREAD

**Issue by Balibaloo** [guopenghui/obsidian-quiet-outline#12]
抱歉我的中文不好，我正在使用谷歌翻译。

如何重现：
1）将插件图标从右侧面板拖到左侧
2) 激活“安静轮廓”热键
3）插件移动到右窗格

这是一个小错误，但很高兴拥有
谢谢你制作了这么酷的插件

**Comment by guopenghui** [comment]
Feel free to use English.
I think I understand this problem,and an `if` will solve it.
You can replace `main.js` with this file below, and this feature will be also included in next formal release. 
[main.zip](https://github.com/guopenghui/obsidian-quiet-outline/files/8408817/main.zip)

**Comment by Balibaloo** [comment]
Awesome, that fixed it!
Thank you!
