### ISSUE TITLE
高亮的标题位置与跳转的标题位置不一致

### ISSUE THREAD

**Issue by HIDE-r** [guopenghui/obsidian-quiet-outline#120]
我感觉很违和, 高亮的标题的位置看起来像是当前页面的最上面一个标题.

而点击标题进行跳转时又是居中跳转

https://github.com/guopenghui/obsidian-quiet-outline/assets/51672711/7e887a00-3776-43f9-b2df-9513bc1ac09f

**Comment by bone1122** [comment]
赞同，建议作者大牛优化，可以参考市面上已经培养用户习惯较熟的产品--飞书、语雀等
1.当页面滚动时，各级标题靠近内容区页面顶部，大纲对应标题高亮选中。
2.点击大纲标题，内容区滚动至标题处，对应标题在该内容区“第一行”展示。

**Comment by sjhsbhqf** [comment]
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/41407099/b0641b03-6b72-48bc-99dd-fcfea06aad0f)
我也有这个问题，如图所示，在浏览到Vscode代码助手最后一个小节的时候，右边目录视图高亮的却是下一个标题

**Comment by ivxoxvi** [comment]
这个问题现在还存在

**Comment by guopenghui** [comment]
我看下后面改成按照光标位置来确定高亮哪个标题吧，或者加个选项。

**Comment by guopenghui** [comment]
Implemented in 0.3.18
