### ISSUE TITLE
Render Markdown Not Working anymore after the update !!!

### ISSUE THREAD

**Issue by Biswanath00** [guopenghui/obsidian-quiet-outline#122]
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/46648233/a44c94b6-61d6-4981-9f86-2daa874a9cba)
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/46648233/270c1623-3943-4adf-8b36-21efefd0a765)

**Comment by Biswanath00** [comment]
I like you Plugin please fix the issue :)

**Comment by guopenghui** [comment]
After a certain update to Obsidian, the sanitizer removed the math lable. This has been resolved and will be released in the next version in the near future. Sorry for the long-waiting...

**Comment by guopenghui** [comment]
0.3.16
