### ISSUE TITLE
插件失效

### ISSUE THREAD

**Issue by Li-Jack** [guopenghui/obsidian-quiet-outline#123]
当我更新我的Obsdian到 版本：v1.3.5 后，我发现插件失效了，无发在右侧的状态栏显示大纲

**Comment by ZenodotusPro** [comment]
我也是显示无效

**Comment by yyh357** [comment]
我也是

**Comment by UryWu** [comment]
我的Obsidian是1.3.5，可以用。试试在ctrl+p里使用：Quiet Outline: Quiet Outline命令打开。

**Comment by yyh357** [comment]
谢谢回复。
图标消失后，设置了快捷键，然后用快捷键可以重新打开图标，正常使用了


杨耀华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guopenghui/obsidian-quiet-outline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月19日(星期三) 凌晨1:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guopenghui/obsidian-quiet-outline] 插件失效 (Issue #123)





 
我的Obsidian是1.3.5，可以用。试试在ctrl+p里使用：Quiet Outline: Quiet Outline命令打开。

**Comment by sidpku** [comment]
> 当我更新我的Obsdian到 版本：v1.3.5 后，我发现插件失效了，无发在右侧的状态栏显示大纲

我认为issue可以被关闭了，@UryWu 的方法可以解决这个问题

> 我的Obsidian是1.3.5，可以用。试试在ctrl+p里使用：Quiet Outline: Quiet Outline命令打开。
