### ISSUE TITLE
希望增加功能: 某个H1标题展开后, 移动到下一个H1标题时, 之前展开的内容不消失

### ISSUE THREAD

**Issue by TouyamaRie** [guopenghui/obsidian-quiet-outline#126]
现在的情况是: 某个H1标题展开后, 移动到下一个H1标题时, 之前展开的内容会消失.; 或者全部展开后, 移动到某个标题, 与当前标题无关的其他展开的内容也会消失. 希望可以增加一个可选功能, 固定展开的内容

**Comment by guopenghui** [comment]
设置里面关掉自动展开，就不会自动折叠了

**Comment by fromXin** [comment]
> 设置里面关掉自动展开，就不会自动折叠了

谢谢您的插件。

关掉自动展开确实不会自动折叠了，但是也不会自动展开了哈哈哈。

希望可以有自动展开的同时，不自动折叠的选项。

谢谢您。

**Comment by guopenghui** [comment]
从版本 `0.3.28` 开始设置了自动展开的其他选项
