### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by albertoloscerritos** [guopenghui/obsidian-quiet-outline#128]
Hi, I was wondering if this project is still active. Thanks

**Comment by guopenghui** [comment]
Yes. Development of new features is slowing down now because of personal health conditions, but maintenance will be done if there are usage problems.😉

**Comment by albertoloscerritos** [comment]
Hi, thanks for the answer :) Hope everything gets better. 

I wanted to ask if you know if the auto expand option is still working, because it does not seem to be working in my system. I'm using obsidian 1.4.14 : 

![quiet-bug](https://github.com/guopenghui/obsidian-quiet-outline/assets/16707033/dee3fde5-36ae-4453-8a93-d0eb2cfc9da4)

Also, I wanted to make a recommendation. An option to set the color or the "theme" for the outline plugin. What do I mean by this, well I think it would look very cool if we could change the color of the text (and of the icons) to the same grey color as the core outline plugin i.e. 
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/16707033/11e11a31-4858-4de3-ad78-162d92e9ac4e)
instead of the white that quiet outlines uses i.e.
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/16707033/4415b4a9-6345-4f00-9664-aff20b3df5de)

Thanks a lot for your time.

**Comment by guopenghui** [comment]
Auto expand works fine for me, but indeed many people complain about this issue. I need more infomation to repruduce it.

Text color will follow system `var(--nav-item-color)` variable since next release.

![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/fcea98af-9ba5-4014-bb7b-98d092a3ba85)

**Comment by guopenghui** [comment]
Problem with auto-expand can be discussed in  #133

**Comment by albertoloscerritos** [comment]
Great news. Thanks :)
