### ISSUE TITLE
功能请求：请问以后会考虑增加像官方大纲插件那样的拖拽功能吗？

### ISSUE THREAD

**Issue by tyf2018** [guopenghui/obsidian-quiet-outline#13]
请问以后会考虑增加像官方大纲插件那样的拖拽功能吗？即：在侧边面板中拖拽层级标题，即可调整对应内容（包括正文）在笔记中的位置，相当于整段内容上移或下移。

谢谢

**Comment by guopenghui** [comment]
暂时不考虑支持这个功能，我主要是有几点考虑：
+ 这个操作涉及到修改笔记内容，操作比较危险，万一对笔记产生什么破坏就糟糕了。现在这个插件里面完全没有任何修改笔记的操作，我觉得算一个优点，用着比较放心。
+ 修改大纲层级这个操作我觉得一般使用频率比较低，重构笔记时偶尔用一下，为此破坏现在插件不修改笔记的特性感觉有点划不来。
+ 官方插件已经有了这个功能，偶尔打开用一下感觉够用了。
+ 现在这个插件本身有一些局限，比如层级只能是连续的，不允许从h1直接跳跃到h3（因为是用一个树组件实现的，父子关系得连续），所以有时未必反映了实际的层级关系，要实现拖拽层级可能会比较复杂。

**Comment by tyf2018** [comment]
> 暂时不考虑支持这个功能，我主要是有几点考虑：

很用心的回答，赞。细想一下，拖拽层级确实属于低频操作
