### ISSUE TITLE
希望不要渲染自定义ID，如图

### ISSUE THREAD

**Issue by jiajiala** [guopenghui/obsidian-quiet-outline#131]
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/73203026/fd0515be-3859-4d71-8e9c-60c266ae7e2c)
希望这个自定义ID不渲染，这个作为外部链接用，但是大纲内会显示
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/73203026/9702d0c0-29c3-49b8-91e0-f119798b1c24)
希望像默认大纲这样

**Comment by guopenghui** [comment]
0.3.16
