### ISSUE TITLE
We Need Update Pls!

### ISSUE THREAD

**Issue by qksuki** [guopenghui/obsidian-quiet-outline#132]
At Obsidian Version 1.4.13, it doesn't work anymore, I really like this plugin and request an update! 😭😭😭😭

**Comment by guopenghui** [comment]
What's the problem? Everything is fine on my end, I'm using version 1.4.13

**Comment by wujun001** [comment]
> What's the problem? Everything is fine on my end, I'm using version 1.4.13

滚动时自动展开不生效。

**Comment by guopenghui** [comment]
> > What's the problem? Everything is fine on my end, I'm using version 1.4.13
> 
> 滚动时自动展开不生效。

@wujun001 设置里面设置了吗

**Comment by wujun001** [comment]
打开了，是编辑模式下不生效，预览模式正常

**Comment by guopenghui** [comment]
> 打开了，是编辑模式下不生效，预览模式正常

构造一个稳定复现的案例吧

**Comment by guopenghui** [comment]
@wujun001 讨论转移到 #133 
@qksuki Please open a new issue with more infomation.

This issue lacks of infomation and will be closed.

**Comment by qksuki** [comment]
> @wujun001 讨论转移到 #133 @qksuki Please open a new issue with more infomation.
> 
> This issue lacks of infomation and will be closed.

感谢回复，事实上问题就是 #133 ，在我更新 0.3.16 后问题依旧没有解决。ob 的版本是 1.4.14，设置中打开了自动展开到对应标题。另外注意身体健康，感谢开发！
