### ISSUE TITLE
Auto-expand not work

### ISSUE THREAD

**Issue by guopenghui** [guopenghui/obsidian-quiet-outline#133]
Need to reproduce.

**Comment by wujun001** [comment]
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/29793989/45236e33-3f27-453d-8a93-7f0f252276dc)
看了下代码，不知道这个对你有没有帮助

**Comment by guopenghui** [comment]
> ![image](https://user-images.githubusercontent.com/29793989/271156219-45236e33-3f27-453d-8a93-7f0f252276dc.png) 看了下代码，不知道这个对你有没有帮助

有帮助。outliner在markdown view的页面里面插入了一个元素，覆盖了整个页面，改变了scroll事件的target（就是你图里面橙色区域 target: div.outliner-plugin-list-lines-scroller）。所以响应scroll事件的函数没有执行。
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/3678ea4c-97fc-46ec-b6db-294750afa47c)

**Comment by QuanPie** [comment]
Hello, I have a same issue, auto-expand does not work well.
---
Obsidian-version: v1.4.14
device: Macbook Air M1, 2020, 14.0
plugin-version: 0.3.16

**Comment by m17129026281** [comment]
确实有问题，我也碰到了。1.4.14。编辑模式下不能自动滚动同步。

**Comment by guopenghui** [comment]
0.3.17
