### ISSUE TITLE
标题内容的开头如果是`- `(-加空格)，那么大纲的显示效果中会自动把`- `给隐藏，请问有解决办法吗或者是否考虑优化？

### ISSUE THREAD

**Issue by xiaotimodunmogu** [guopenghui/obsidian-quiet-outline#134]
请问作者是否考虑优化一下这个显示效果，不胜感激呀，非常期待。
![ECFPQQ6QCOXU8R0JV Y}JZ8](https://github.com/guopenghui/obsidian-quiet-outline/assets/104133993/bd6ace9a-4c54-4b5e-8233-9165d2a260fe)
![VUF5U~L(B@_EFKWEXT$JE4U](https://github.com/guopenghui/obsidian-quiet-outline/assets/104133993/6b59b292-b25c-45ad-a31e-bbb94c3dcbba)

**Comment by guopenghui** [comment]
我猜是把这个格式当初列表渲染了，所以把开头的-和空格去掉了。下一版我改一下

**Comment by xiaotimodunmogu** [comment]
> 我猜是把这个格式当初列表渲染了，所以把开头的-和空格去掉了。下一版我改一下

非常期待，非常感谢！

**Comment by guopenghui** [comment]
0.3.17
