### ISSUE TITLE
Feature Request: show where you're at in outline

### ISSUE THREAD

**Issue by dlccyes** [guopenghui/obsidian-quiet-outline#14]
In Typora or HackMD you can see the position you're at in the outline pane, which is incredibly useful when navigating through long notes. Is it possible to add this feature to this amazing plugin?

screenshot of Typora's implementation  
![image](https://user-images.githubusercontent.com/32875990/162631365-093e01f3-3110-4958-b5ed-1503fc749cad.png)

HackMD's implementation  
![image](https://user-images.githubusercontent.com/32875990/162632888-9fc5ebc4-01c6-4ded-8df3-8ccc7c50f4dc.png)

**Comment by guopenghui** [comment]
I'll look into this.

**Comment by ManasMadrecha** [comment]
Yes, this feature will be very useful. Similar to VS Code's option of follow the cursor's position.

**Comment by guopenghui** [comment]
Supported in release `0.2.4`
![auto_expand](https://user-images.githubusercontent.com/13451866/167258545-291f6986-bee8-4140-8804-75b1d2431cf2.gif)

**Comment by dlccyes** [comment]
Thanks! Sublime implementation! Couldn't ask for more.
