### ISSUE TITLE
[Feature Request] 收起的状态下，高亮展示当前所在的位置的已展开的最深层级标签

### ISSUE THREAD

**Issue by yushaw** [guopenghui/obsidian-quiet-outline#140]
需求：
收起的状态下，高亮展示当前所在的位置的已展开的最深层级标签。

详细说明：
如下结构的大纲：
- 1
  - 1.1 
- 2

在1.1 被收起的状态下，如果当前位置在 章节 1.1，目前大纲不会有任何高亮。

期望: 章节 1 被高亮。

**Comment by ryanwwest** [comment]
I came here to propose the same FR. I usually have only 1-2 levels of heading visible from Quiet Outline, but have many subsections and I can't quickly see where I'm at if I'm in a subsection.

**Comment by guopenghui** [comment]
Implemented in 0.3.18
