### ISSUE TITLE
本次更新后右侧边栏没有标签了

### ISSUE THREAD

**Issue by ivxoxvi** [guopenghui/obsidian-quiet-outline#147]
![WechatIMG312](https://github.com/guopenghui/obsidian-quiet-outline/assets/53618104/b61484aa-59a5-495b-96d8-a9a77bd29167)

**Comment by guopenghui** [comment]
用命令重新打开一下试试？

**Comment by ivxoxvi** [comment]
> 用命令重新打开一下试试？

感谢，用命令打开就显示了，但还是无法随着插件启用按钮的关闭和开启显示。

**Comment by guopenghui** [comment]
嗯，目前不会随插件打开而自动打开面板

**Comment by guopenghui** [comment]
0.3.20开始默认会在启动插件时打开
