### ISSUE TITLE
Headings in outline unfold automatically when you start typing and don't auto fold when opening a new note?

### ISSUE THREAD

**Issue by jontoki** [guopenghui/obsidian-quiet-outline#148]

**Comment by guopenghui** [comment]
Can you record a video or gif? I'm not sure where the problem is. And which version of obsidian do you use now?

**Comment by guopenghui** [comment]
It's the core outline plugin, not quiet outline. You can open quiet outline with command `Quiet Outline`.

Quiet outline looks like:
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/2354e96b-629a-45da-a645-ab9106aeb701)

Maybe I should make it auto-open when turning on the plugin. By the way, this annoying auto-expand-when-input feature of core outline is exactly the reason I develop quiet outline.

**Comment by jontoki** [comment]
Ohh okay this fixed it, I had no idea I had to do this command (I should've looked at the community page for this, I usually just add a plugin without reading too deeply into it. Thank you for your time and sorry for the trouble
