### ISSUE TITLE
项目符号是X）时目录上下会出现空白间隙过大的问题

### ISSUE THREAD

**Issue by srun007** [guopenghui/obsidian-quiet-outline#150]
如图所示，当项目编号为 x）的格式时
![6c0ca3d477236b850f8dd859d2b2821](https://github.com/guopenghui/obsidian-quiet-outline/assets/80263694/aebf3993-35e2-4332-ae8c-4114ca51b537)
![6b410bb4ce97d5002a2946657a258cb](https://github.com/guopenghui/obsidian-quiet-outline/assets/80263694/0f5359ac-feb4-4d53-aee9-3091215ca990)
ob版本：1.53
quiet outline版本：0.3.19

还有按住ctrl键不会显示预览，可能是和系统级别的预览或者hover editor冲突了。偶尔会调出hover editor的整个界面的预览。所以建议增加一个自定义设置其它键的选项。

**Comment by srun007** [comment]
我目前的办法是4\）用转义字符，但是这毕竟是临时的办法。

**Comment by guopenghui** [comment]
应该是被渲染成列表了，我后面看一下。

**Comment by srun007** [comment]
谢谢。希望这个插件越来越好。挺好用的。
