### ISSUE TITLE
大纲字体太紧凑

### ISSUE THREAD

**Issue by aiqyqy** [guopenghui/obsidian-quiet-outline#158]
![1](https://github.com/guopenghui/obsidian-quiet-outline/assets/55039821/05b6f419-4ef6-4e16-9ce9-4f2e8bf7ba66)

如上图所示，大纲字体边距太紧凑，字体大小、样式无法调节，与topora相比不够爽朗。

**Comment by guopenghui** [comment]
这个主要是为了在同一屏下显示更多信息而设置得紧凑的。

可以写一个CSS snippet自定义需要的高度：
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/3c68aa25-527b-43d7-86e6-5506d71dbb74)

**Comment by aiqyqy** [comment]
> 这个主要是为了在同一屏下显示更多信息而设置得紧凑的。
> 
> 可以写一个CSS snippet自定义需要的高度： ![image](https://private-user-images.githubusercontent.com/13451866/309128387-3c68aa25-527b-43d7-86e6-5506d71dbb74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDAyOTEsIm5iZiI6MTcwOTI5OTk5MSwicGF0aCI6Ii8xMzQ1MTg2Ni8zMDkxMjgzODctM2M2OGFhMjUtNTI3Yi00M2Q3LTg2ZTYtNTUwNmQ3MWRiYjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEzMzMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YTk5YWRlZWJmYmVjNzNhMzRiODY2NTNmMzkzYjAxZGVjY2QyNDQzNDY4MTg0NjBjM2RmYmFiZmVkMjVjMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7jioCWsq1muRA4J74Cyspcisix5MyCllCYrtNKsKr9k)
![1](https://github.com/guopenghui/obsidian-quiet-outline/assets/55039821/4d142e33-90ea-4923-a99d-e92f152f17f4)
老哥，按照这个方法只对第一级大纲生效啊。
还有obsidian的字体立体感不强、颜色很浅，看起来灰蒙蒙的很费劲，咱有typorn那种看起来比较爽朗的主题吗，我换了几个主题都无法解决这个问题：blue topaz、typora-vue、atom。

**Comment by guopenghui** [comment]
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/e617660f-d997-4daa-bd61-0fcca3100de3)
奇怪了，我这里每一级都起效了。要不看看在元素那里看看为什么没有起效

颜色浅应该还是主题或者样式的原因，在元素那里查看一下，到底是哪个样式起效了。我用的是things：
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/c9f62360-bc67-4954-9f67-d0c964cc9640)

**Comment by guopenghui** [comment]
我看了一下，字体的颜色是跟随ob默认的字体颜色，和内置大纲的字体颜色保持一致。
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/4c78bc40-d2e2-4046-b5c5-90f0d9f0cda2)
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/6048658d-b474-4245-afdf-943a0b95dc6f)

改这个常量的值：
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/12b8f4d5-abdd-4833-bd27-7fc703c5f6e5)
