### ISSUE TITLE
Adding a new heading collapses the tree

### ISSUE THREAD

**Issue by offset-torque** [guopenghui/obsidian-quiet-outline#159]
Firstly, thank you for this useful plugin, it makes crowded documents much easier to work.

**Problem:** If I add a new heading to a document, tree collapses to H1 level automatically.

**Solution:** Please keep the tree expansion same as before if user adds a new heading.

I have these options **ON** but tree still collapses with a new heading:
- Expand headings to certain level: ON
- Default expand level: 2
- Remember expanded/collapsed state of headings of opened notes: ON

**Comment by guopenghui** [comment]
check `0.3.26`

**Comment by offset-torque** [comment]
Thank you very much for this fix **guopenghui** :)
