### ISSUE TITLE
Trim heading (Stop soft-wrap)

### ISSUE THREAD

**Issue by shalintj** [guopenghui/obsidian-quiet-outline#16]
Hey there! Just installed the plugin. Is it possible to trim headings in the outline? Right now, all the heading flow to the next line (aka, soft-wrap is enabled).

**Comment by guopenghui** [comment]
Modifying CSS file can achieve this.
But what if heading is too long? If hiding it, some contents can't be seen.
![image](https://user-images.githubusercontent.com/13451866/163090416-5a4b368d-191a-4b3c-8f62-c7dcede5afb1.png)

**Comment by shalintj** [comment]
Can you help me with the CSS for the same?

So, the reason why I want to trim long headings is it makes them easily skimmable. I use the Quiet Outline plugin to quickly access headings for longer notes. And for that, just 2-3 words of a heading are enough to identify where I want to go.

Can you help me with the CSS for trimming / let the headings overflow in the plugin?

**Comment by guopenghui** [comment]
Yes, add this rule to `styles.css` or snippets folder :

![image](https://user-images.githubusercontent.com/13451866/163123701-b14ca655-8669-461e-8ed2-734d78bf611a.png)

**Comment by shalintj** [comment]
It worked. Thanks a lot.
