### ISSUE TITLE
Feture Request: 在canvas中导航

### ISSUE THREAD

**Issue by longguzzz** [guopenghui/obsidian-quiet-outline#161]
希望可以在quiet outline里边显示group，并以group之间的嵌套包含关系组织成树结构，在点击之后跳转到相应位置

**Comment by guopenghui** [comment]
调研了一下，应该可以实现。

有个问题是节点应该如何命名大纲中的heading，group是有名字的可以直接用，文本节点应该怎么命名比较好。
我的想法是可以使用文本中的第一个标题作为名字，但不是所有笔记中都有标题，这时使用第一行的内容作为名字，如果太长就截断。

**Comment by longguzzz** [comment]
这样挺好的。

另外可能还要考虑的是，group层级是否要和text里边的标题层级合在一起展示？如果直接展示的话，canvas下直接的group、子groups、nodes这样是加了三个层级，不过也有可能套更多层。可能需要某种使二者具备高区分度的方式综合展示。

**Comment by guopenghui** [comment]
`0.3.25`
