### ISSUE TITLE
Quiet Outline interfering with Command Palette

### ISSUE THREAD

**Issue by beglitched** [guopenghui/obsidian-quiet-outline#162]
I have several commands pinned in Command Palette that don't show up as pinned when activating Command Palette. Put vault in restricted mode and reactivated plugins one by one. Turning on Quiet Outline is what triggered the issue. 

Here is my Command Palette when Quiet Outline is not enabled:
![CleanShot 2024-03-29 at 09 55 30](https://github.com/guopenghui/obsidian-quiet-outline/assets/58926565/9f6d8522-9d91-49e3-85d9-521451bb46a7)

Command Palette when Quiet Outline is enabled:
![CleanShot 2024-03-29 at 09 54 57](https://github.com/guopenghui/obsidian-quiet-outline/assets/58926565/82bbe88d-d9c0-40ac-89d2-74bb2cd9ea94)

**Comment by guopenghui** [comment]
Can't reproduce that.

With quiet-outline closed:
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/e012d34e-28d8-478d-a37a-8a8cc8ddea8a)

![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/b4f57c22-6b3e-4b11-82f8-8f2907900098)

Then open it:
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/75d522e4-7f42-4994-a9e7-9cdf8a8e16e6)

![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/f7901fff-1dfc-42fe-a080-d60e9d1156e1)

No command is been hidden.

You can retry in a new vault and find a minimal reproduction.
