### ISSUE TITLE
彩虹大纲线显示不出来

### ISSUE THREAD

**Issue by Murano-Satomi** [guopenghui/obsidian-quiet-outline#165]
大佬你好，我把设置里的全开了，彩虹大纲先就是显示不出来，请问如何解决

![Snipaste_2024-04-10_20-36-08](https://github.com/guopenghui/obsidian-quiet-outline/assets/65110931/be0f56f2-ea9f-4734-b7d3-a6490ec27c5c)

**Comment by guopenghui** [comment]
换个主题试试？我这边是能出来的

![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/ec1011c7-6f41-4b6b-8836-20cdd91c8bb3)

**Comment by Murano-Satomi** [comment]
是的，我用的 Blue Topaz 主题，换回默认主题就能显示了，我再琢磨琢磨看看 哪个css 冲突了
