### ISSUE TITLE
quiet outline working in new windows

### ISSUE THREAD

**Issue by nefesh1-almagor1** [guopenghui/obsidian-quiet-outline#168]
The plugin does not support exploration or navigation in notes opened in a new window

**Comment by guopenghui** [comment]
Click outline panel first, then select note in new window. After that, you can navigate with outline.

![recording](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/a0fc0ee5-ff61-46c3-9c1c-8de8c8820892)

**Comment by nefesh1-almagor1** [comment]
Thanks for the answer, but the question I have is that while you are browsing different headers in a note in a new window, the plugin does not track that is, the text focus in the right panel, the navigation by clicking on a header in the right panel works, and even the note headings are recognized in the right panel.


Uploading video.mp4…

**Comment by nefesh1-almagor1** [comment]
Thanks for the answer, but the question I have is that while you are browsing different headers in a note in a new window, the plugin does not track that is, the text focus in the right panel, the navigation by clicking on a header in the right panel works, and even the note headings are recognized in the right panel.


https://github.com/guopenghui/obsidian-quiet-outline/assets/72080184/9f8e680c-4e0b-4499-8a2b-9fb4cdf497d2

**Comment by nefesh1-almagor1** [comment]
Thanks for the answer, but the question I have is that while you are browsing different headers in a note in a new window, the plugin does not track that is, the text focus in the right panel, the navigation by clicking on a header in the right panel works, and even the note headings are recognized in the right panel.

![video](https://github.com/guopenghui/obsidian-quiet-outline/assets/72080184/9b0dfb4e-1038-4647-945d-07181ca51fbe)

**Comment by guopenghui** [comment]
test in `0.3.33`

**Comment by nefesh1-almagor1** [comment]
thank you so much
