### ISSUE TITLE
Filtering is not effective

### ISSUE THREAD

**Issue by Archie-2021** [guopenghui/obsidian-quiet-outline#17]
When i try to filter, it just open up some folding, not eliminating any results. like i am having a lot of level 3 heading I use to index stuff and i can find anything because there is no filter applied.

thank you, such a plugin was really needed

**Comment by guopenghui** [comment]
Yes, filter doesn't eliminate any heading. It only add a thin underline to the selected heading. 

![image](https://user-images.githubusercontent.com/13451866/163165098-1f51976b-e201-460e-b492-f2e2b6132e5e.png)

**Comment by guopenghui** [comment]
If you want headings un selected to be eliminated, replace `main.js` file in plugin folder to this `main.js` file below：
[main.zip](https://github.com/guopenghui/obsidian-quiet-outline/files/8481245/main.zip)

 and add a rule in `styles.css`：
![image](https://user-images.githubusercontent.com/13451866/163176517-40de8ac7-3a65-470a-9d4c-3007d9f9decf.png)
then that's it：
![image](https://user-images.githubusercontent.com/13451866/163177104-d3ad0ac1-5778-4184-b294-95793730a7da.png)


I'll consider making it a formal release later.

**Comment by guopenghui** [comment]
Now there is no need to modify `style.css` file, as hiding irrelevent results is supported inrelease `0.2.4`  . You can enable it in settings.

**Comment by Archie-2021** [comment]
> Now there is no need to modify `style.css` file, as hiding irrelevent results is supported inrelease `0.2.4` . You can enable it in settings.

It works like a charm now, thanks
