### ISSUE TITLE
希望在“自动展开”选项开启的同时，其它目录部分能够保持之前设置的展开层级，而不会自动把其它的标题都折叠到只有1级

### ISSUE THREAD

**Issue by Richardggm** [guopenghui/obsidian-quiet-outline#172]
目前的情况是，在“自动展开”选项开启的时候，如果它发挥作用了，那么其它层次的标题，全都会折叠到只有一级目录。

比如说之前设置的折叠到3级目录，那么一旦我到了某个地方编辑，那里的层级更小，自动展开了，总的目录都会折叠到只有一级目录。

这一点不太方便，因为很多时候，还是希望目录大致维持在设定的展开层级，方便看和找。

所以，希望能够在“自动展开”选项开启的同时，能够保持设置的展开层级，而不会自动把其它的标题都折叠到只有1级。

**Comment by guopenghui** [comment]
嗯，我考虑一下

**Comment by Richardggm** [comment]
谢谢，辛苦了

**Comment by guopenghui** [comment]
测试一下 `0.3.27` https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.27

**Comment by Richardggm** [comment]
更新使用了，感谢大佬。 

**提议：**
希望能够再有一个选项：自动展开当前标题的时候，其它之前展开的标题能够折叠到原来设定的层级。 
就是说，除了目前正在阅读和编辑的部分的标题会展开，其它之前展开了的，又回到了原来的折叠状态。只不过不是之前那样，折叠到了最小的1级，而是可以折叠到当前设置的那个展开层级。


**原因：**
因为试用了新的选项“仅展开当前标题”，发现有一个问题，就是新的选项，它展开得太多了。 
比如说原来设置的是展开到2级标题。当一个笔记比较长，有很多5级，6级等标题的时候，如果浏览下来，它会把很多4,5,6级的小标题都展开。然后一直维持在展开状态。这样想找2级标题就不太方便。


**详细描述：**
所以希望能够再有一个选项：当你要编辑某一部分，它自动展开当前标题到对应层级的时候，能够让其它部分的标题，折叠回自己设置的层级，比如说2级。   就是说，只把你当前专注编辑的部分自动展开，其它没在编辑的，就算之前阅读时候展开了，希望能够折叠回之前设置的层级，例如2级。

希望您有空的时候，能够再考虑下。

**Comment by Richardggm** [comment]
当然，最近新加的这个选项也有它的用处，希望也能够保留。 因为不同的文件长度，可能就需要不同的设置会更加方便。

**Comment by guopenghui** [comment]
我想是不是设置成“展开到当前设置的层级”呢？ 就是那个层级切换器设置的层级。感觉这样更通用一些

如果平时不用这个切换器，那它默认就是一直在默认层级的。 如果手动设置了，那就按设置的来。

比如说你的默认层级是 2，那打开文件时这个切换器的状态就是 2，标题自动恢复到 2级展开。
如果你手动设置到 3，那标题就自动恢复到 3级展开

**Comment by Richardggm** [comment]
是的，我指的也是这个切换器的设置。  不在视线焦点上的目录，就恢复到这个层级。

现在有两个层级设置，一个是设置页面的“默认层级”。另外一个是外面界面上的切换器的设置。 
因为这个“默认层级”是所有文件共用的。太固定了。   但是切换器的设置，是可以不同文件，设置不同的展开层级。 后者要更加灵活一些。

**Comment by guopenghui** [comment]
之前那个默认其他标题全部折叠的方案干脆去掉吧，变成折叠到默认层级。
现在有四种设置：
+ 展开同时，折叠其他到默认层级
+ 展开同时，折叠其他到切换器的层级
+ 仅展开，不折叠
+ 关闭自动展开

**Comment by Richardggm** [comment]
可以的。 因为如果需要全部折叠，那相当于直接把切换器层级设置为1是一样的效果。

**Comment by guopenghui** [comment]
可以测试一下 `0.3.28`

**Comment by Richardggm** [comment]
测试了，很完美。感谢大佬

**Comment by Richardggm** [comment]
反馈：好像出现了bug，"记忆展开状态"的功能没有了。 当我把第一个笔记的层级切换器设置为3，然后切换了另外一个笔记之后再切换到第一个笔记，第一个笔记的展开状态不见了，折叠成了默认展开状态（我设置的默认展开状态为1）

**Comment by guopenghui** [comment]
应该是切换笔记的时候，会触发一下光标位置变化的事件，然后就触发“自动展开”了，后面我看怎么改一下

**Comment by Richardggm** [comment]
主要是切换文件之后，原来文件的“层级切换器”的层级会被重置掉，又变成“默认层级”。如果“层级切换器”的这个层级切换，能够在切换文件，或重新打开关闭文件之后被记忆住就好了。
