### ISSUE TITLE
更新后出现一个问题

### ISSUE THREAD

**Issue by kafkapara** [guopenghui/obsidian-quiet-outline#173]
特别特别棒的一个插件，但最近更新以后发现不能自动展开了，我反复检查了，依旧不能使用。希望大神能够解决这个问题，感谢！

**Comment by guopenghui** [comment]
检查设置了吗，前面的更新增加了自动展开的设置项

**Comment by guopenghui** [comment]
能不能录一个视频，或一个gif，我看下具体什么情况下有这个问题

**Comment by guopenghui** [comment]
![recording](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/529f89d0-1180-41cb-b86f-1829e85beacd)

我这里是这么设置的，可以自动展开
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/13451866/ac466c1b-5ab7-407f-8d89-84354c05fffe)

**Comment by kafkapara** [comment]
文章和大纲，两者是互相匹配的。例如，当光标随意指向一个二十万字文档中的任意一个位置时，大纲页面则会自动显示此文章中含有的H1、H2、H3等。大纲的显示是随着文档的工作而进行的，自动显现。

您在图中的自动展现，没问题。但之前使用插件的时候，有一个自动跳转功能。随着文章用光标放置在某段落上，大纲会相应的自动显示，这对于长篇文档比较重要。

我之前用这个插件的时候，觉得您真是个天才，这种长篇文档非常需要这种大纲的自动显现。

实在是抱歉，因为文章内容不太适合截图，所以不能用动态方式显示。也耽误了您的时间，再次抱歉。只是一个长期受益于您的一位普通使用者的一点困惑。

**Comment by guopenghui** [comment]
`0.3.30` 修复了这个问题

**Comment by kafkapara** [comment]
非常感谢！已更新，可正常使用。
