### ISSUE TITLE
[Feature request] add to show full name of the heading when hovering over it 

### ISSUE THREAD

**Issue by Archie-2021** [guopenghui/obsidian-quiet-outline#18]
This is a very basic feature needed, I wonder why nobody complains about it , it is very annoying for me

thank you

**Comment by guopenghui** [comment]
Can you offer some image examples? Every heading displays its full name in my outline: 
 
![image](https://user-images.githubusercontent.com/13451866/163178941-e1eaebc6-57be-4761-aa0d-4a88246c184a.png)

**Comment by Archie-2021** [comment]
> Can you offer some image examples? Every heading displays its full name in my outline:
> 
> ![image](https://user-images.githubusercontent.com/13451866/163178941-e1eaebc6-57be-4761-aa0d-4a88246c184a.png)

i think it is because all your headings are too short so have no problem, here one example:

![image](https://user-images.githubusercontent.com/85870778/163222887-5ccc323e-9a7a-400f-ae0d-0e64ef3d8ed1.png)

**Comment by guopenghui** [comment]
I guess it's because you use `_` instead of white space so heading can't be breaked to words.

**Comment by Archie-2021** [comment]
> I guess it's because you use `_` instead of white space so heading can't be breaked to words.
> 
> Maybe adding a CSS rule can solve this, I'll check it tomorrow.

it is plausible explanation, i kinda like it to be each heading in every new line, multiline could be more confusing.

**Comment by guopenghui** [comment]
With Ellipsis mode, extra words should be hided and replaced as `...`. There should be no words wraped to next line.

Anyway, maybe this is the most preferable solution 🧐：
![image](https://user-images.githubusercontent.com/13451866/207550177-efa6a91a-8790-4831-b4e0-5af15899425c.png)

**Comment by ryanwwest** [comment]
Ah you're right. I guess I meant that when Ellipsis mode is off, not on, the multiline effect occurs. Some sort of indent or other marker for additional lines of the same heading might still improve readability. But yes, something like that popup text on hover seems helpful for ellipsis mode.

**Comment by guopenghui** [comment]
[`0.3.13`](https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.13) supports this feature.

**Comment by Archie-2021** [comment]
> [`0.3.13`](https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.13) supports this feature.

Excellent, thank you
