### ISSUE TITLE
replie issue #168

### ISSUE THREAD

**Issue by nefesh1-almagor1** [guopenghui/obsidian-quiet-outline#180]
Hello, a couple of weeks ago I raised issue #168 in which I attached a gif image about the problem, but I could not follow up on your response, the problem persists and is the following: the main window of the plugin recognizes the headers and even accompanies exploration. In the secondary window the plugin also recognizes the headers, but it does not accompany the exploration, thank you for your time and response

**Comment by guopenghui** [comment]
Dont need to open a new issue, just talk about this problem in #168
