### ISSUE TITLE
更新插件后出现bug，按下“to bottom”这个按钮后，最顶部的部分会被隐藏起来

### ISSUE THREAD

**Issue by Richardggm** [guopenghui/obsidian-quiet-outline#181]
本来顶部应该是这样：
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/35445448/4f7f91ce-ce30-4577-9866-b1534b160d71)

结果变成这样：
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/35445448/637b2053-a898-4dd3-b889-04a0c95d2301)

**Comment by guopenghui** [comment]
是只有quiet ouline 有这个问题吗

你用的是哪个主题？

**Comment by Richardggm** [comment]
> 是只有quiet ouline 有这个问题吗
> 
> 你用的是哪个主题？

好像是我弄错了，应该不是插件的文件。我换到旧版本插件，还是出现这个问题。  这个问题有时候出现，有时候又恢复正常。所以暂时先不管它了。

**Comment by guopenghui** [comment]
有可能和主题的实现有关系。之前我也发现我这个插件发生过这种情况，但是只在某个主题下会发生。

后来我发现是我用的那个主题在实现某个样式的时候，一个地方没有处理精细，一个竖条设置的太长了，导致大纲标题自动滚动的时候，把整个面板都带着上去了。

**Comment by Richardggm** [comment]
> 有可能和主题的实现有关系。之前我也发现我这个插件发生过这种情况，但是只在某个主题下会发生。
> 
> 后来我发现是我用的那个主题在实现某个样式的时候，一个地方没有处理精细，一个竖条设置的太长了，导致大纲标题自动滚动的时候，把整个面板都带着上去了。

谢谢告知。  用的，ITS theme主题。  之前没出现这个问题。 早上突然出现了。 发现主要是一个很长的文件，编辑就容易出现这个。  不过后面又恢复正常了。

**Comment by guopenghui** [comment]
嗯，如果有稳定复现的步骤，可以告诉我，我来查一下
