### ISSUE TITLE
侧边栏图标失效

### ISSUE THREAD

**Issue by ProudBenzene** [guopenghui/obsidian-quiet-outline#183]
如图所示，原先的大纲图标消失了，重新变回了默认的图标：

<img width="350" alt="image" src="https://github.com/guopenghui/obsidian-quiet-outline/assets/93238080/a1dd1fa4-98b0-401a-9441-d023cc9b8c15">

**Comment by guopenghui** [comment]
是更新的原因吗？你现在的obsidian版本是多少

**Comment by ProudBenzene** [comment]
我明白了，是iconic插件导致的问题，关掉插件后就恢复正常了。

对您造成的打扰感到万分抱歉，感谢您开发出如此强大简洁的插件！

**Comment by guopenghui** [comment]
没事~
