### ISSUE TITLE
大纲下发有一块区域无法正常显示

### ISSUE THREAD

**Issue by JawnSong** [guopenghui/obsidian-quiet-outline#184]
Obsidian版本：win桌面版1.6.3
quiet outline版本：0.3.35
![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/172829887/aca620b5-1a4c-4b22-98f7-352b7d2cbd5c)

**Comment by guopenghui** [comment]
我后面改一下。

这个是之前加的，因为底部状态栏会挡住内容。后来ob更新了样式，自带了padding，还加了左边那个底栏，导致这个遮挡变得更高了。。

**Comment by guopenghui** [comment]
见 0.3.36
