### ISSUE TITLE
hidden header

### ISSUE THREAD

**Issue by nefesh1-almagor1** [guopenghui/obsidian-quiet-outline#186]
Hello, the plugin does not display the header properly, in fact the lower headers are not even shown, navigation is only possible with the headers visible in the right sidebar, in the latest versions the navigation through the headers lost fluidity and smoothness, I I would like the navigation to be like in version 0.3.25 of the plugin.

![Captur](https://github.com/user-attachments/assets/9fb3ad7d-03e9-427f-9b95-138a7c5765e7)

**Comment by guopenghui** [comment]
This problem should have been fixed in latest version, so closed.
