### ISSUE TITLE
Feature Request: Collapse All Button

### ISSUE THREAD

**Issue by robbpriestley** [guopenghui/obsidian-quiet-outline#187]
Hello

Please consider adding a button that will collapse all nodes.

When I do work, and expand a bunch of nodes, the workspace gets messy, and I need a way to reset it so it looks nice and quiet again.

Thank you!

**Comment by guopenghui** [comment]
There is a reset button on the top of outline panel, does this fit your need?

**Comment by robbpriestley** [comment]
Oh, do you mean the "Level Switch"? Yeah okay. That works.

**Comment by guopenghui** [comment]
![image](https://github.com/user-attachments/assets/f3169fb0-38f9-4e15-a7ee-82849531430c)

This buttton

**Comment by robbpriestley** [comment]
Yes, that works also.

It's in the "**Search Support**" option, which I had turned off. (I keep most of the options turned off, but I love this plugin, it really helps a lot! Thanks!)
