### ISSUE TITLE
how to add a purple color theme which compatible with obsidian purple theme

### ISSUE THREAD

**Issue by JustusPan** [guopenghui/obsidian-quiet-outline#19]

**Comment by guopenghui** [comment]
There are lots of CSS rules to be set. For example, a button, you have to set diffrent rules for its border, inner, shadow when it's hovered, focused, and blured, in both light and dark theme.🤯 I'll continue look into this issue and try to find a reasonable approach.

**Comment by guopenghui** [comment]
`0.3.14` supported some color settings, hope this will offer some help.

**Comment by JustusPan** [comment]
decent solution. thank for your effort
