### ISSUE TITLE
Bug: Slow Conversion to Code

### ISSUE THREAD

**Issue by Riffaells** [guopenghui/obsidian-quiet-outline#196]
And now more specifically. Selecting plain text and converting it to a code block using three backquotes (```) causes performance slowdown. This is observed when this operation is used repeatedly, and the delay becomes noticeable.

---

Steps to reproduce
---

- Paste or type text into the editor

<details><summary>My example Code</summary>

```typescript
type Todo = {
  id: number;
  task: string;
  completed: boolean;
};

class TodoList {
  private todos: Todo[] = [];
  private idCounter: number = 1;

  addTask(task: string): void {
    const newTodo: Todo = {
      id: this.idCounter++,
      task,
      completed: false,
    };
    this.todos.push(newTodo);
    console.log(`Task added: "${task}"`);
  }

  completeTask(id: number): void {
    const todo = this.todos.find((todo) => todo.id === id);
    if (todo) {
      todo.completed = true;
      console.log(`Task with ID ${id} marked as completed.`);
    } else {
      console.log(`Task with ID ${id} not found.`);
    }
  }

  listTasks(): void {
    this.todos.forEach((todo) =>
      console.log(
        `[${todo.completed ? "✔" : " "}] ${todo.id}: ${todo.task}`
      )
    );
  }
}

// Usage Example
const myTodoList = new TodoList();
myTodoList.addTask("Learn TypeScript");
myTodoList.addTask("Build a project");
myTodoList.listTasks();
myTodoList.completeTask(1);
myTodoList.listTasks();
```
</details>

- Select this text.
- Press the backquote (`) key three times in a row to convert the text to a code block.

---

Report
---

![r](https://github.com/user-attachments/assets/97520759-3d3b-40de-afc6-2d55efdd2981)

[Trace.json](https://github.com/user-attachments/files/17922976/d.json)

**Comment by guopenghui** [comment]
I'm not quite sure I've understood your case. Is it like this:

![PixPin_2024-11-27_20-01-55](https://github.com/user-attachments/assets/d9416adf-2aeb-498b-8a7e-37ae37070cab)

**Comment by Riffaells** [comment]
I was wrong, it's most likely not because of Quiet Outline


https://github.com/user-attachments/assets/3ea50f69-2162-41b5-ba31-1da6921880e3
