### ISSUE TITLE
FR: Open Quiet Outline on Obsidian start

### ISSUE THREAD

**Issue by acepelon** [guopenghui/obsidian-quiet-outline#197]
I always want Quiet Outline in my right sidebar when I start Obsidian, every time I shut Obsidian down, something else ends up in the sidebar, forcing me to open QO again.  I have tried doing this with the macro feature in Quick Add like:
![image](https://github.com/user-attachments/assets/3e404b65-6cfd-4af6-b7fd-aaf46cbc8519)

![image](https://github.com/user-attachments/assets/f467454b-fe63-40bb-afe6-636f13004706)

but it doesn't appear to work.  Could we add this feature to always open QO in a sidebar?  I use this every day and I love it.

Thanks!
ACE

**Comment by guopenghui** [comment]
By default, obsidian will restore last workspace layout in next launch so there is no need to open QO by hand. This works well for me and not sure why your QO doesn't auto open.

**Comment by acepelon** [comment]
ok, well shucks.  I have the same problem on multiple vaults on multiple computers, but if it is just me I won't waste any more of your time.  Thanks for responding and take care.

ACE
