### ISSUE TITLE
Heading text enclosed in bacticks appears as blank

### ISSUE THREAD

**Issue by greetclammy** [guopenghui/obsidian-quiet-outline#199]
```
# `Text in backticks`
```
shows up as blank in Quiet Outline, unlike in the core Outline plugin, which displays content enclosed in backticks.

Use case: headings in technical documentation may contain text enclosed in backticks e.g. https://help.obsidian.md/web-clipper/filters

**Comment by guopenghui** [comment]
This should work.
![image](https://github.com/user-attachments/assets/8361c563-9ea7-4b51-808d-ca8166639927)

**Comment by greetclammy** [comment]
It does, the problem was my custom CSS. Apologies!
