### ISSUE TITLE
feature：重新启动ob后，大纲能够自动出现在侧边栏

### ISSUE THREAD

**Issue by Masktial** [guopenghui/obsidian-quiet-outline#2]
似乎现在每次关掉ob后再启动，就要重新运行命令调出插件的大纲。
能够保持插件大纲吗？不受ob启动关闭影响？

谢谢你的插件~！

**Comment by guopenghui** [comment]
在我这边好像是只要前一次关obsidian的时候不主动关掉这个插件，下一次启动时候就还在

**Comment by Masktial** [comment]
我看了下应该是和某个插件或外观有冲突。可惜我没找出是哪一个插件。

现状是：
每次打开后，原来有大纲的位置就会变为空白。
重新运行后，才会正常显示大纲。

**Comment by guopenghui** [comment]
控制台有没有报一个警告说“vue没有挂载(mount)成功”？ 
如果是的话，我刚刚解决了这个问题，下次更新release的时候改过来
