### ISSUE TITLE
大纲自动滚动

### ISSUE THREAD

**Issue by yanwanchen720** [guopenghui/obsidian-quiet-outline#20]
- 文件名滚动效果：
>当文件名过长时会滚动显示
![image](https://user-images.githubusercontent.com/72399630/165870690-c2e26676-1b69-45b3-91b8-3ea948e201d5.png)

- 希望大纲中也可以加入滚动效果：
>![image](https://user-images.githubusercontent.com/72399630/165870925-0e7b0823-18ea-4b30-b3d1-82eb9e3f6a63.png)

**Comment by guopenghui** [comment]
尝试加了一个这个功能，应该能满足同样的需求
![image](https://user-images.githubusercontent.com/13451866/204073518-6ea6b52e-e6d8-4b11-81f8-b2a6eb9a78da.png)

**Comment by yanwanchen720** [comment]
嗯嗯，可以加一个这样的开关，需要的话可以自行打开，期待显示效果👍

**Comment by guopenghui** [comment]
在`0.3.7`中加入了该功能，打开“省略长标题”选项时，就会在悬浮时显示标题内容

**Comment by yanwanchen720** [comment]
好的👌☺️
