### ISSUE TITLE
自动展开，跳转BUG

### ISSUE THREAD

**Issue by que1jue** [guopenghui/obsidian-quiet-outline#200]
# 版本信息
Obsidian：1.7.7
插件版本：0.3.38
# 1. 自动展开问题
标题展开后不会缩回之前展开的标题，只会施行展开动作，没有缩回动作
![image](https://github.com/user-attachments/assets/d41d22cf-4361-43ec-a9c3-0df629529195)
设置中将“自动展开”选项设置为：仅展开当前标题。图中至上而下进行滑动，及时已到下一一级标题，之前的标题也不会收回
回退个人更新前版本0.3.25正常
# 2. 标题跳转显示常亮
在大纲中点选标题直接跳转到对应标题后，后续滑动界面，先前的跳转的高亮会一直保持，并且高亮当前的标题
![image](https://github.com/user-attachments/assets/1090e52c-a641-4565-a168-5d74b6976284)
点选1处标题进行跳转，手动滑动到2处时，跳转时的高亮依旧存在。这个好像一直都有，之前没注意过
版本0.3.25也有此情况
# 3. 大纲线好像没了...
可能是Obsidian版本更新的原因？因为回退0.3.25版本也没有出现，印象里之前是正常显示的

**Comment by guopenghui** [comment]
“仅展开当前标题” 的逻辑就是这样的，意思是只管展开，不自动折叠。
你需要的应该是“展开同时折叠剩余标题到默认层级”

大纲线我这边还是在的，可能是主题影响。换个主题或者切换到默认主题试试。

第二点我这边是正常的，后面我再测试一下。

**Comment by que1jue** [comment]
已解决
# 1. 自动展开选项配合“默认层级”以及“层级切换器”可以达到旧版效果
# 2. 3. 经测试是主题Blue Tpoz的问题，默认主题或其他个别主题没有此现象
