### ISSUE TITLE
FR: Add regex filtering for headings

### ISSUE THREAD

**Issue by ManasMadrecha** [guopenghui/obsidian-quiet-outline#22]
Currently the headings are filterable using fuzzy search, but it would be great if there are options to add more advanced functionality like "Exclude certain headings", e.g., `!dontsearchthis` or "Exact match", e.g., `=searchthisonly`.

**Similar to**: 
1. https://github.com/nothingislost/obsidian-bartender 's search filter bar
2. Fuse.js

**Comment by ManasMadrecha** [comment]
@guopenghui Since you are using Vue, can you use v-model to take the regex string in the Input box and filter the headings using it? A very little VS Code-style button can be added if one wants to enable regex search.

**Comment by guopenghui** [comment]
Supported in `0.3.0`: 

![image](https://user-images.githubusercontent.com/13451866/168220395-e6da3f47-65ef-455a-8884-0fa6a5e101c3.png)
