### ISSUE TITLE
FR: Collaborate with `Creases` plugin to collapse content if Headings are collapsed from the Outline

### ISSUE THREAD

**Issue by ManasMadrecha** [guopenghui/obsidian-quiet-outline#23]
Reference: https://github.com/liamcain/obsidian-creases

Currently, `Creases` plugin is able to leverage the core Outline plugin to collapse body content if Headings are collapsed from Outline view. It would be great if the same functionality worked with the more feature-rich Quiet Outline plugin.

**Comment by guopenghui** [comment]
Can you describe more details about the workflow? I read `Creases`'s readme but didn't figure out how to interact with core Outline plugin.

**Comment by ManasMadrecha** [comment]
With `Creases` plugin installed, we can do this: If some Heading is collapsed manually by us in the Core Outline, then the Content Body's corresponding heading is also automatically folded. Of course, this is an optional setting in Creases plugin, but it's a good one. And it works the other way around too, i.e., if Heading is folded in Body, then it gets folded in Outline too.

**Comment by ManasMadrecha** [comment]
You can maybe check these on how to sync:
- https://github.com/liamcain/obsidian-creases/blob/e405a0ec20e267b9f8d081678cc7bb7759026ccd/src/main.ts#L114
- https://github.com/liamcain/obsidian-creases/blob/e405a0ec20e267b9f8d081678cc7bb7759026ccd/src/main.ts#L349

**Comment by guopenghui** [comment]
It seems that `Creases` cannot expand leaf heading by operating outline, because leaf headings in core outline view don't have collapse/expand button (quiet-outline neither)：

![image](https://user-images.githubusercontent.com/13451866/167305077-533a2beb-26ae-4515-b72f-1c04278f81f0.png)

Moreover, `auto-expand` doesn't work well with this featrue, with the same reason. Because leaf headings in outline cannot be expanded, so (leaf) cotents in note cannot be revealed.

**Comment by ManasMadrecha** [comment]
What are leaf headings? Headings without any sub-heading?

**Comment by guopenghui** [comment]
> What are leaf headings? Headings without any sub-heading?

Yes, leaves of heading tree.

**Comment by ManasMadrecha** [comment]
So, if they have no subheadings, they need not be expanded any way. 

For parent headings, maybe, it's something Creases does on its own, instead of leveraging core Outline? That's why, I said it's good that both such amazing plugins (Creases and Quiet Outline) collaborate directly, rather than trying to add some code via Quiet Outline. Maybe they can update their code to include Quiet Outline too.

--------

Regarding, auto-collapas feature of Quiet Outline, then yes, it will be an "either or" feature, which we can enable in setting. Like, either have auto expand/collapse while scrolling OR have Creases sync enabled.

**Comment by guopenghui** [comment]
Creases's implementation is quite simple, it modifys `core outline`'s prototype and make every click on heading trigger an update for fold state. It doesn't interact with `core outline` but changes `core outline`'s behavier.

If `quiet-outline` wants to do so, it doesn't need `creases`.

**Comment by guopenghui** [comment]
About leaves, for example you have a note like this: 

- Heading Level 1
  - Heading Level 2  (leaf)
     - some content

`Heading Level 2` is a leaf heading, if it doesn't expand, `some content` below it can not be showed out. But leaf headings in outline panel have no expand button and cannot expand.

**Comment by ManasMadrecha** [comment]
Oh, now I get your point. Yes, the Outline won't have any button to collapse a Heading, if such heading has no subheadings, even if the Heading's body has normal text content in it. 

I think this is logical. We don't need the `quiet-plugin` to collapse such leaf headings. That we can do manually by visiting a Heading in the Body, and using already available Hotkey to `Toggle Fold`. 

For Parent Headings though, it would be nice to have this feature, i.e., use the Sidebar Outline pane to quickly fold such parent headings we want, and automatically the Body will shrink too. The use-case is that, with such shrunken Body, we have to scroll little and it is easy to read a particular section, by quickly unfolding only that section using `Toggle Fold` Hotkey. 

-------

> If quiet-outline wants to do so, it doesn't need creases.

Then, that's even better. 😃
