### ISSUE TITLE
Option to turn off search input box and other button.

### ISSUE THREAD

**Issue by ChurchillDu** [guopenghui/obsidian-quiet-outline#24]
First of all, thanks for your work.
I'm kind of "ocd", could you add a option to turn on or off other functions? I wanna remove the top button that I barely use.
![image](https://user-images.githubusercontent.com/62705137/167268781-8792ea1d-77ce-4782-9cc0-9b5d6a2e8c4f.png)
I'm appreciate if you take my issue, while it's fine if you're too busy to do it.
thanks again.

---

首先非常感谢您开发的插件。
我有点儿强迫症，能不能增加开启或关闭其它功能的选项？上方的按钮我几乎不用，所以我想去掉。
我这个要求比较小众，您要是开发忙可以不用管我。
再次感谢。

**Comment by ManasMadrecha** [comment]
You could simply hide it with CSS snippet.

```css
.quiet-outline .function-bar {display: none !important}
```

This will hide the huge input box and the green button, but will keep the subtle slider to choose which Headings to show and collapse.

**Comment by ChurchillDu** [comment]
> You could simply hide it with CSS snippet.
> 
> ```css
> .quiet-outline .function-bar {display: none !important}
> ```
> 
> This will hide the huge input box and the green button, but will keep the subtle slider to choose which Headings to show and collapse.

It work perfectly! Much appreciated.
