### ISSUE TITLE
FR: Auto Scroll the Outline to always keep current `.located` class Heading within view

### ISSUE THREAD

**Issue by ManasMadrecha** [guopenghui/obsidian-quiet-outline#25]
### Issue

Currently, the plugin adds a new `.located` class to a heading based on Content Body's scroll position. That's great. We can customize it in CSS snippet. 

But, on a long page containing hundreds of headings, such `.located` heading quickly goes below the view. The issue is that when the Current Heading goes out of view in the Outline, it's hard to know where you are in your long document. 
So, we have to manually scroll the Outline again and again. 

It would be great if such Current Heading (with class `.located`) stays in view, i.e., the Outline pane is able to auto scroll. 

-------

It can be something along these lines:

```js
function keepTocInViewMethod() {
  const tocNavEl = document.querySelector("#yourOutlineDivWithScrollbar");
  const tocItemEls = document.querySelectorAll(".n-tree-node.located");
  const tocItemEl = tocItemEls[tocItemEls.length - 1]; // last item

  if (tocItemEl && tocNavEl) {
    let tocItemElOffsetTop = tocItemEl.offsetTop - 300;

    tocNavEl.scrollTop = tocItemElOffsetTop;
  }
}
```

And call this function on the `scroll` event, i.e., whenever the Content Body is scrolled. 
- You can dabble with `debounce` too if it gives better performance. 
- Also, you can add this event listener only if there are over, say 10 Headings on a page, i.e., 10 `.n-tree-node-wrapper` elements.

```js

    if (/* There are over 10 headings */ <Headings>.length > 10) {
<TheContentBodyElement>.addEventListener(
        "scroll",
        _.debounce(keepTocInViewMethod, 1000),
        null
      );
    }
```

**Comment by guopenghui** [comment]
I find it can be achieved by `Element.scrollIntoView()`，seems good.

![keep_in_view](https://user-images.githubusercontent.com/13451866/167291965-ccb5121c-7c8c-4ca9-b49d-f7c0fc9673bd.gif)

**Comment by ManasMadrecha** [comment]
Superb, superb, superb! 
That's exactly my request. Kindly release it ASAP. Stay blessed. ❤️

**Comment by guopenghui** [comment]
Supported in `0.3.0`
