### ISSUE TITLE
FR: Drag and drop option to rearrange headings like the Core Outline plugin

### ISSUE THREAD

**Issue by ManasMadrecha** [guopenghui/obsidian-quiet-outline#26]
Kindly add this feature which is available in Core Outline plugin.

**Comment by ManasMadrecha** [comment]
Reference: https://www.naiveui.com/en-US/dark/components/tree#drag-drop.vue

**Comment by injoylin** [comment]
这个功能真的太重要的，markdown以致只有原生的obsidian能做到，vscode都不行，强烈希望我们插件能做到拖拽标题，排列层级

**Comment by guopenghui** [comment]
Supported in `0.3.12`
