### ISSUE TITLE
Bug: outline not shown after switching to another note while searching

### ISSUE THREAD

**Issue by dlccyes** [guopenghui/obsidian-quiet-outline#29]
When you switch to another file with something in the search box, nothing will be displayed. You'll have to clear the search and switch again to make the outline show.

As shown in the gif

![](https://i.imgur.com/wMKrsjd.gif)

[higher quality version](https://i.imgur.com/y6Deyna.gif)

**Comment by guopenghui** [comment]
Vue component refresh error. Fixed in `0.3.0`

**Comment by dlccyes** [comment]
So the bug this issue described is fixed, but it seems like the default search becomes whole word match. Need to switch on the "regex search" option for it to show partial match.

Is that intended?

Regex Search off
![image](https://user-images.githubusercontent.com/32875990/168239589-3355bac5-f42b-46f7-9823-853745cd6866.png)

Regex Search on
![image](https://user-images.githubusercontent.com/32875990/168239597-a350dc1c-996c-45c5-9e82-134dbb67b338.png)

I'll close it since this issue itself is fixed.

**Comment by guopenghui** [comment]
Oh, no. That's a mistake! 
https://github.com/guopenghui/obsidian-quiet-outline/blob/7fda230763dfb70a9e23e40977be01391863f6f7/src/Outline.vue#L211

It should be: 
`return option.label.toLowerCase().contains(pattern.toLowerCase())`

**Comment by guopenghui** [comment]
Fixed in `0.3.1`
