### ISSUE TITLE
outline disappear when quiet outline window get the focus by mouse click

### ISSUE THREAD

**Issue by Qiguang** [guopenghui/obsidian-quiet-outline#30]
![Obsidian_Q1SDc2WhKE](https://user-images.githubusercontent.com/10783991/168707145-22834867-3c24-4415-9b1a-a22cd9c9135e.gif)
Obsidian version 0.14.6
quiet outline version 0.3.1

**Comment by guopenghui** [comment]
安装版本是多少？
![image](https://user-images.githubusercontent.com/13451866/168722510-28be51a1-8b0d-4a82-8c20-50f8999e11ce.png)
我这里没有这个问题，怀疑是新版本有什么变化。

**Comment by Qiguang** [comment]
安装程序版本 v0.14.2

**Comment by guopenghui** [comment]
你应该把这个面板拖到中间了，拖到左边或右边就不会有这个问题了。

因为拖到了中间，所以当点击大纲面板的时候，就会改变当前的`activeLeaf`，可以看到上面出现了一个紫色的条， 但是大纲面板本身并没有自己的标题，所以就显示no data了。

拖到两边：
![xxx](https://user-images.githubusercontent.com/13451866/168738676-2ed73858-f544-4367-9958-c277202e97d6.gif)

**Comment by Qiguang** [comment]
ok，确实是如你所说
