### ISSUE TITLE
暗黑模式下的字顏色

### ISSUE THREAD

**Issue by w7536214** [guopenghui/obsidian-quiet-outline#32]
<img width="287" alt="image" src="https://user-images.githubusercontent.com/67720976/169561759-7ecf9744-44ad-4512-ac0c-4fb4bc9b14d0.png">

請問如何更改暗黑模式下的字顏色，謝謝

**Comment by guopenghui** [comment]
一般暗黑模式下字颜色是白的，不会这么暗。
是不是从明亮模式切换过来的？如果是的话点一下左上角的重置按钮就好了。
