### ISSUE TITLE
[Appearance] Invisible text in light mode

### ISSUE THREAD

**Issue by dummifiedme** [guopenghui/obsidian-quiet-outline#34]
Plugin works amazingly on dark mode, but the text is invisible on light mode of any theme (tried on Sanctum, Minimal, and default).

Would really help if it could be fixed :) 
Thanks

![image](https://user-images.githubusercontent.com/68785729/171815394-ec3b7c36-101e-42d9-8a21-a2d677da0264.png)

**Comment by guopenghui** [comment]
Click reset buttun and it will toggle to light mode

**Comment by guopenghui** [comment]
Toggling between light/dark mode needs an additional click on reset button, which is a tradeoff for performance. 

To detect light/dark mode change, you have to watch the `class` attribute change of `body` all the time，which is too heavy for such a low-frequency situation.
