### ISSUE TITLE
Shortcut for refresh button 

### ISSUE THREAD

**Issue by jiewangjs** [guopenghui/obsidian-quiet-outline#35]
First, I just want to say how good the plugin is !
![图片](https://user-images.githubusercontent.com/11204422/171861812-173bf03c-b2c2-4309-a42f-3bdb7460c247.png)
Add shortcut key to the refresh button show in above image ? 
Refresh button can be frequently needed, i.e. a handy shortcut can be extremely helpful.

**Comment by guopenghui** [comment]
A command `reset expanding level` has been added in [0.3.2](https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.2)  and you can set a shortcut-key on it in obsidian's setting.
