### ISSUE TITLE
请问经常出现no data是怎么回事呢

### ISSUE THREAD

**Issue by GRELEEN** [guopenghui/obsidian-quiet-outline#36]
点击大纲后也不能正常跳转至相应内容部分

**Comment by guopenghui** [comment]
按`ctrl+shift+i`，看看控制台有没有什么报错呢？ 或者能否发个截图或动图？

**Comment by GRELEEN** [comment]
我试了一下，在右侧栏的话可以正常使用，但是托出独立窗口后，点击大纲级别后立马出错，需要重启软件，谢谢你的回复







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guopenghui/obsidian-quiet-outline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月18日(星期六) 下午5:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guopenghui/obsidian-quiet-outline] 请问经常出现no data是怎么回事呢 (Issue #36)





 
按ctrl+shift+i，看看控制台有没有什么报错呢？ 或者能否发个截图或动图？

**Comment by guopenghui** [comment]
> 我试了一下，在右侧栏的话可以正常使用，但是托出独立窗口后，点击大纲级别后立马出错，需要重启软件，谢谢你的回复

独立窗口我还没看，我现在还是14.5版本。 后面正式更新15版本后我看一下

**Comment by Wcdaren** [comment]
我也遇到这个问题 ，而且还是100%的 ；

**Comment by guopenghui** [comment]
> 我也遇到这个问题 ，而且还是100%的 ：我去点目录（该插件），点击后，就会触发原本的文件失焦，然后该插件就会no data，可能是文件失焦后，没有缓存，所以就no data了

是这个原因。 0.15对原先软件逻辑改动挺大，等官方`0.15`正式版本出来我统一改

**Comment by guopenghui** [comment]
新版本中已经解决
