### ISSUE TITLE
New sidebar focus breaks plugin

### ISSUE THREAD

**Issue by yeruvan** [guopenghui/obsidian-quiet-outline#38]
Recently Obsidian started allowing you to treat the right sidebar as your current focus pane. This Quiet Outline impossible to use. When I toggle controls on Quiet Outline, it thinks the focus note is the plugin tab itself, and shows nothing. When I click back on my note, the controls are reset.

To see reproduction and behavior, see this video:

https://forum.obsidian.md/t/new-sidebar-focus-has-made-some-plugins-unusable/39056

Windows 11, Obsidian 0.15.2, plugin version 0.3.1

**Comment by guopenghui** [comment]
Current `Obsidian 15.0` is under insider build, I'll check it when formal edition is released. 
Thanks for your feedback!

**Comment by guopenghui** [comment]
It is solved in #43
