### ISSUE TITLE
给作者大大提几个小优化需求

### ISSUE THREAD

**Issue by Kolooooo** [guopenghui/obsidian-quiet-outline#4]
感觉这插件要火🔥
提几个需求：
- [[|别名]]，链接别名作为标题在大纲中的优化（如图1）
- 大纲对齐线的需求（如图2）
- 显示大纲面板的快捷键设置，毕竟屏幕就那么点，快捷键切换文件目录与大纲目录还是很常用的（如图3）

望考虑，感谢兄弟提供这么好用的功能

<img width="792" alt="image" src="https://user-images.githubusercontent.com/19557102/159603980-b1cd677b-0cf5-46b4-bd5b-7239a0e7b0ba.png">

<img width="284" alt="image" src="https://user-images.githubusercontent.com/19557102/159604426-f2ccf858-9c27-4d1d-b639-1059f134870f.png">

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/19557102/159604198-21691cfc-b090-48a7-9e08-46df582180a1.png">

**Comment by guopenghui** [comment]
感谢使用！
别名这个应该挺常用，我研究一下。
第三个显示大纲面板这个，不知道直接用打开面板的那个命令`quiet outline`能不能满足要求？感觉和第三张图里那个命令的功能差不多，都是没打开的时候打开，打开的话切换过去

**Comment by Kolooooo** [comment]
quiet outline 是可以调出大纲面板，但大纲面板好像挪位了以后，再 quiet outline 又回到原位置了，这是个问题

**Comment by Kolooooo** [comment]
tab1、tab2的切换，比较直观操作
![Untitled](https://user-images.githubusercontent.com/19557102/159631559-0d69070e-cb8a-4c28-939e-3271bbe72752.gif)

**Comment by guopenghui** [comment]
别名和大纲对齐线搞定了~

快捷键切换我没太搞明白，这两个tab是通过什么快捷键切换的？

**Comment by Kolooooo** [comment]
就是设置快捷键打开大纲界面

**Comment by Kolooooo** [comment]
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/19557102/162117412-1d17c5df-f143-4a01-b53f-3d7d75bed3e0.png">
刚更新了新版，快捷键切换可以使用了，看上图快捷键设置

**Comment by guopenghui** [comment]
嗯嗯，应该是有命令（command）就可以设置一个快捷键。
