### ISSUE TITLE
在切换深浅颜色主题的时候，文字显示上会有问题

### ISSUE THREAD

**Issue by chenxin0397** [guopenghui/obsidian-quiet-outline#40]
![202108161359350001001](https://user-images.githubusercontent.com/73974352/177008201-0eb86476-9a1e-4ee7-a4c5-39197ac919b6.gif)
如图所示吧，在明亮主题的模式下切换到黑暗主题，文字仍然还是深色的，只能关闭，重启之后文字才变成白色。好像只能通过关闭重启来解决。

**Comment by chenxin0397** [comment]
而且关掉之后再开，这个插件的面板显示还有一点问题。

**Comment by guopenghui** [comment]
和 #32 是同样的问题

 

> 而且关掉之后再开，这个插件的面板显示还有一点问题。

具体还有什么问题呢？

**Comment by huyiwen** [comment]
还有类似的问题，当使用[这个主题](https://github.com/ceciliamay/obsidianmd-theme-primary)的时候，输入框外一圈的颜色和主题不一致。
![Screen Shot 2022-07-03 at 15 52 38](https://user-images.githubusercontent.com/5737212/177030548-87895ff2-88ed-4259-9b79-b970c766365e.png)
![Screen Shot 2022-07-03 at 15 53 12](https://user-images.githubusercontent.com/5737212/177030566-c2e5bb28-ab39-488a-8a6d-6f61cd099a6f.png)

**Comment by chenxin0397** [comment]
> 和 #32 是同样的问题
> 
> And # 32 are the same problem
> 
> > 而且关掉之后再开，这个插件的面板显示还有一点问题。There is also a problem with the panel display of this plug-in.
> 
> 具体还有什么问题呢？
> 
> What's the problem, exactly?
请看上图，我本来是明亮模式转黑暗模式，切换后，面板上的文字看不见
然后我关掉了OB再次打开，这时quiet-outline面板显示是有问题的，点了我自定义的刷新按钮之后quiet-outline/面板才显示正常
也就是说关闭OB再次打开的时候，quiet-outline面板显示是不正常的

**Comment by guopenghui** [comment]
软件的版本和安装版本是多少？ 

我本地没有复现出来(我是`0.14.15`的版本)，关闭再打开还是正常显示的，还在原来的位置。

**Comment by chenxin0397** [comment]
> 软件的版本和安装版本是多少？
> 
> 我本地没有复现出来(我是`0.14.15`的版本)，关闭再打开还是正常显示的，还在原来的位置。

我是同样的版本号，不知道是不是我的win10系统有问题？
