### ISSUE TITLE
软件更新v0.15.6版本后 在大纲内点击不能跳转标题

### ISSUE THREAD

**Issue by Einspieler19** [guopenghui/obsidian-quiet-outline#42]
在大纲内点击任意标题，正文部分不会进行跳转。是软件v0.15.6版本更新后出现的。

**Comment by hustrjh** [comment]
Same problem!

**Comment by guopenghui** [comment]
收到，我这几天研究一下新的机制，尽快改！

**Comment by guopenghui** [comment]
在 [0.3.2](https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.2) 中解决了这个问题✅

**Comment by Einspieler19** [comment]
> 在 [0.3.2](https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.2) 中解决了这个问题✅

好了 牛逼
