### ISSUE TITLE
It stoped working

### ISSUE THREAD

**Issue by Drakemoor** [guopenghui/obsidian-quiet-outline#43]
After I updated to Obsidian 0.15.6, clicking on any header in the sidebar does nothing. It doesn't jump to that header in the file editor. 
Please help.

**Comment by misteramazingyt** [comment]
Seconding this - I'm having the same issue

**Comment by shen-me-gui** [comment]
yeah,I encountered the same situation。
in quiet-outline sidebar，Every time I click, the label will be expanded。
clicking on any header in the sidebar does nothing

**Comment by guopenghui** [comment]
I noticed this issue and it will be fixed in couple of days. 😉

**Comment by GHz** [comment]
> I noticed this issue and it will be fixed in couple of days. 😉

Nice

**Comment by guopenghui** [comment]
fixed in [0.3.2](https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.2) ✅

**Comment by GHz** [comment]
It works again indeed ! Thanks for this quick fix.

**Comment by Drakemoor** [comment]
Thank you!
