### ISSUE TITLE
[Feature Request] Add a hotkey for focusing outline search

### ISSUE THREAD

**Issue by dlccyes** [guopenghui/obsidian-quiet-outline#44]
I use the search option a lot and it would be nice if there's a configurable **hotkey to focus the search box**.

(currently there are only hotkeys for focusing the outline pane & resetting expanding level)

**Comment by guopenghui** [comment]
Good idea.  I add a command `Focus on input` and you can replace `main.js` with this：
[main.zip](https://github.com/guopenghui/obsidian-quiet-outline/files/9125663/main.zip)

May publish it in next update.

**Comment by eblanshey** [comment]
I would use this too if you released the new version. Thanks!

**Comment by guopenghui** [comment]
Updated in `0.3.3`
https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.3
