### ISSUE TITLE
Bug: can't interact with Quiet Outline in standalone window

### ISSUE THREAD

**Issue by Qupci** [guopenghui/obsidian-quiet-outline#45]
With the new update, I use multiple Obsidian windows across Virtual Desktops, but only the main window can have expandable sidebars. The temporary solution for me, is to move the sidebars contents into a new window, which then can be accessible over all Virtual Desktops. But there is a **bug** with Quiet Outline, is that, when it is in standalone window, you can't interact with it. The core plugin doesn't have this issue.

Besides fixing the bug, another way to solve my issue navigating with Quiet Outline with absence of sidebars is would be the ability to open a new instance of Quiet Outline in each window as the new pane. I'm not sure, if it is worth it to implement for now.

**Comment by guopenghui** [comment]
I haven't figure out the mechanism of multi-window yet and I guess this bug has something to do with `vue.js`. Once I understand it , it will be fixed. 😉

**Comment by guopenghui** [comment]
fixed in `0.3.7`
