### ISSUE TITLE
Clicking on header doesn't jump to position in Obsidian v0.15.6

### ISSUE THREAD

**Issue by RyanQuey** [guopenghui/obsidian-quiet-outline#46]
Before the feature works great, and even now on my other computer that still is on Obsidian v0.14 it works fine as well, but something seems to have happened on a recent version that breaks it so clicking on a header doesn't jump to that position in the editor. 

PS this is a great plugin, much prefer this outline over the obsidian default.

**Comment by guopenghui** [comment]
Did you update plugin version to `0.3.2`? In latest version this problem is fixed.

**Comment by RyanQuey** [comment]
It does indeed! Works great. Sorry I should have checked earlier.
