### ISSUE TITLE
Headings collapse even when forbidden

### ISSUE THREAD

**Issue by NomarCub** [guopenghui/obsidian-quiet-outline#47]
Even with expand level set to H5 and auto expand and hide unsearched turned off, headings are collapsed sometimes. It looks like with H5 expand level, H2 headings are collapsed for some reason.

**Comment by NomarCub** [comment]
For example, here I'd expect `H2 1` to be expanded.
![image](https://user-images.githubusercontent.com/5298006/180028967-386a3564-d2e0-4539-b7ee-00115fd96aa5.png)

These are my settings:
![image](https://user-images.githubusercontent.com/5298006/180029206-b6516674-6297-4182-8c54-de5fe6b202de.png)

**Comment by guopenghui** [comment]
Yes, it's a bug. Switching between notes in the same leaf dosen't change the `view` object, so outline level is not to be refreshed.

 If you want to fix it right now, replace `main.js` with this: 
[main.zip](https://github.com/guopenghui/obsidian-quiet-outline/files/9160515/main.zip)

**Comment by guopenghui** [comment]
Fixed in `0.3.3`
https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.3

**Comment by NomarCub** [comment]
It occurs again. Please reopen and fix this.
