### ISSUE TITLE
don't show "no data"

### ISSUE THREAD

**Issue by liangzh-404** [guopenghui/obsidian-quiet-outline#48]
showing "no data" feels like there is something wrong, but it's just because we don't have a header, which is very normal. I suggest we can remove this~

**Comment by guopenghui** [comment]
`naive-ui` added this since some version. I didn't find a method to remove it.😢

**Comment by liangzh-404** [comment]
> `naive-ui` added this since some version. I didn't find a method to remove it.😢
> 
> https://www.naiveui.com/en-US/light/components/tree

get it. I used a simple css snippet to hide it. It worked so let it be~

**Comment by guopenghui** [comment]
Fixed in `0.3.3`
https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.3
