### ISSUE TITLE
增加高亮的自定义选项；跳转后高亮显示标题

### ISSUE THREAD

**Issue by AiurArtanis** [guopenghui/obsidian-quiet-outline#5]
@guopenghui 

---
## 建议

1. 希望**Quiet Outline**的高亮色能支持自定义，例如增加开关控制是否使用主题的醒目色（Accent Color）
2. OB默认的大纲在跳转后会`高亮显示`选中的标题，目前**Quiet Outline**似乎没有这样的效果，希望作者能支持

## 环境

OS：win10
OB：V0.13.33
QO：0.1.2

## 最后

很有潜力的插件，待完善之后可以作为默认大纲的上位替代😁

**Comment by AiurArtanis** [comment]
> 第一条的高亮色是指什么呢？

抱歉没有说清楚，指的是这些绿色部分
![绿色高亮](https://user-images.githubusercontent.com/98091664/159826867-de6b83e2-1495-4001-9877-3bb4c229f7c7.png)

**Comment by KeithW0726** [comment]
这里建议可以和style setting联动，style setting插件里面有统一的accent color设定，这样就不用单独配置，同时也能跟minimal主题适配了

**Comment by AiurArtanis** [comment]
> 这里建议可以和style setting联动，style setting插件里面有统一的accent color设定，这样就不用单独配置，同时也能跟minimal主题适配了

是的，我也建议作者能把一些样式开放style setting配置

**Comment by guopenghui** [comment]
跳转后高亮在`0.2.2`实现了

**Comment by dlccyes** [comment]
希望 accent color 是單獨放在 plugin settings 而非跟 Style Settings 聯動，因為不是所有人都有用那個 plugin （或者也可以兩個都做？在 settings 增加一個選項問是否跟 Style sSttings 聯動之類的）

**Comment by guopenghui** [comment]
`0.3.14` 里支持了颜色设置，支持调整主颜色和大纲线的颜色，可以试一下

**Comment by dlccyes** [comment]
> `0.3.14` 里支持了颜色设置，支持调整主颜色和大纲线的颜色，可以试一下

更新後線的顏色都不見了欸

<img width="285" alt="image" src="https://user-images.githubusercontent.com/32875990/208861374-5cbbcd75-7eff-4980-adda-dae451198cd3.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/32875990/208861528-5a6e7c46-956a-4deb-b9d8-ec02bf58db9d.png">

**Comment by guopenghui** [comment]
[styles.zip](https://github.com/guopenghui/obsidian-quiet-outline/files/10276493/styles.zip)

换一下这个styles.css吧

我第一次上传后发现程序里面有个bug就改了一下，然后只重新传了main.js。但是现在看来styles.css的版本也必须匹配

**Comment by web8823** [comment]
請問之後會不會考慮把大綱普通字體改成稍微灰色/淺色，因為在夜間模式下的普通字體和粗體字看起來都是差不多的白色，比較難一眼區分，各 heading 間的間距也可以微調大一點點🙏。

**Comment by guopenghui** [comment]
> 請問之後會不會考慮把大綱普通字體改成稍微灰色/淺色，因為在夜間模式下的普通字體和粗體字看起來都是差不多的白色，比較難一眼區分，各 heading 間的間距也可以微調大一點點🙏。

众口难调，这个可以通过写个CSS片段来调整到自己满意的样式吧

**Comment by web8823** [comment]
> > 請問之後會不會考慮把大綱普通字體改成稍微灰色/淺色，因為在夜間模式下的普通字體和粗體字看起來都是差不多的白色，比較難一眼區分，各 heading 間的間距也可以微調大一點點🙏。
> 
> 众口难调，这个可以通过写个CSS片段来调整到自己满意的样式吧

好 我研究下 謝謝
