### ISSUE TITLE
Headings collapse past Default Level with Auto Expand enabled

### ISSUE THREAD

**Issue by depascalis** [guopenghui/obsidian-quiet-outline#51]
Headings collapse past the set Default Level when Auto Expand is enabled.

**To Reproduce**
1. Set Default Level to H1
2. Enable Auto Expand
3. Refresh the Quiet Outline Panel
   - _All H1 headings will expand_
4. Set focus on the document and scroll within the document until the Outline panel updates
   - _All H1 headings will collapse in the Outline except for the one in the middle of the document view_

**Expected Behavior**
* All H1 headings should always be expanded
* The outline should also expand the heading currently visible in the document view, even if it is eg. a H4
* All other headings beyond H1 should be collapsed (except for the one visible in the document view)

**Example of Expected Behavior**
_Quite Outline Panel_
* H1
  - H2
  - H2 
* H1
  - H2
  - H2
    - H3
      - H4 (currently visible in document view)
  - H2 
* H1
  - H2
  - H2

**Comment by guopenghui** [comment]
Latest version should fix this issue, as it offers more auto-expand options
