### ISSUE TITLE
More Obvious Look For Active Heading

### ISSUE THREAD

**Issue by Archie-2021** [guopenghui/obsidian-quiet-outline#52]
Just adding bold to active heading (in auto expand mode) is not enough. Can you please add a option to making it more obvious like highlighting it or something.

Also the headings color in light mode shown white too. I usually use Dark mode but still a issue. Not sure it is theme related or note.

Thanks

**Comment by guopenghui** [comment]
For problem 1, you can change to desired appearance at `location` section in `styles.css`.

![image](https://user-images.githubusercontent.com/13451866/185744792-27b67686-1085-41d7-ad10-1b7f9224964d.png)

like `background-color:yellow;`

![image](https://user-images.githubusercontent.com/13451866/185745032-5cc6ea27-0dfe-42cf-a24f-a7c5d1cea58c.png)



For problem 2 , same as #34

**Comment by Archie-2021** [comment]
> For problem 1, you can change to desired appearance at `location` section in `styles.css`.
> 
> ![image](https://user-images.githubusercontent.com/13451866/185744792-27b67686-1085-41d7-ad10-1b7f9224964d.png)
> 
> like `background-color:yellow;`
> 
> ![image](https://user-images.githubusercontent.com/13451866/185745032-5cc6ea27-0dfe-42cf-a24f-a7c5d1cea58c.png)
> 
> For problem 2 , same as #34

Thanks, it is going to get deleted on a new update if I modify it? how i can keep a change if i make one?

**Comment by guopenghui** [comment]
I think it wiil. When updating plugin, old CSS file may be overrideed by new one.

You can create a custom CSS file in obsidian appearance setting and add above rules into it.

Custom css files have the highest priority and doesn't change after plugin updating.

**Comment by Archie-2021** [comment]
> I think it wiil. When updating plugin, old CSS file may be overrideed by new one.
> 
> You can create a custom CSS file in obsidian appearance setting and add above rules into it.
> 
> Custom css files have the highest priority and doesn't change after plugin updating.

Thank you, works like a charm
