### ISSUE TITLE
增加一个复制大纲的按钮

### ISSUE THREAD

**Issue by rRy96693** [guopenghui/obsidian-quiet-outline#57]
参照smart toc这个功能 Smart TOC - Chrome 应用商店
https://chrome.google.com/webstore/detail/smart-toc/lifgeihcfpkmmlfjbailfpfhbahhibba
![image](https://user-images.githubusercontent.com/109261861/187926850-5939ce8c-ffc5-4a1a-8464-2cbf5ea9f047.png)

**Comment by guopenghui** [comment]
已实现，设置为了一个命令，下个版本中添加该功能

**Comment by guopenghui** [comment]
`0.3.3`中已实现
https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.3
