### ISSUE TITLE
两个功能需求

### ISSUE THREAD

**Issue by hdg8087** [guopenghui/obsidian-quiet-outline#6]
【1】目前能一键折叠大纲，希望也能一键展开所有层级。
【2】大纲层级线。
【3】文章内容很多、大纲层级很多的时候，我就想给一级标题上个颜色或者加粗之类的，这样一看就知道繁杂的大纲分为多少个大块。

**Comment by hdg8087** [comment]
哦，是三个需求

**Comment by AiurArtanis** [comment]
> 【2】大纲层级线。

+1

**Comment by tyf2018** [comment]
> 一键展开所有层级

+1

**Comment by hdg8087** [comment]
感谢！
