### ISSUE TITLE
Invisible white text in light mode

### ISSUE THREAD

**Issue by Missionary2112** [guopenghui/obsidian-quiet-outline#60]
As you can see in the image below, it's very hard to see the texts in light mode. I would like the texts to be blended in the system color. In dark mode, the text is already white so there is no trouble there. 

![2022-10-04_21 01 50_CSX](https://user-images.githubusercontent.com/98799613/193978820-a99f1abc-aad1-43d2-b3ca-1d53cfe0bd0e.jpg)

**Comment by guopenghui** [comment]
Same as #34
