### ISSUE TITLE
[问题]标题中的高亮在大纲中没有被渲染出来

### ISSUE THREAD

**Issue by a15355447898a** [guopenghui/obsidian-quiet-outline#62]
![image](https://user-images.githubusercontent.com/62456287/197534228-4beae583-865b-469a-8f3a-22141f7151fd.png)

**Comment by guopenghui** [comment]
已经实现，下个版本更新

![image](https://user-images.githubusercontent.com/13451866/197548181-6d09d650-1c7d-44b9-8073-e6433261057d.png)

**Comment by guopenghui** [comment]
`0.3.4`中已支持，详情见https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.4
