### ISSUE TITLE
Follow Obsidian 1.0 style and support theming

### ISSUE THREAD

**Issue by NomarCub** [guopenghui/obsidian-quiet-outline#63]
The plugin should follow the default Obsidian style:
- the same fold icon
- align indent guide to the middle of the fold icon
- make indent level padding the same

It also should allow to make these things configurable, by using the same variables that Obsidian makes available for themes and snippets in app.css
- accent color - now links in the outline are purple even when the accent color is set to green, which affects all other internal links
- indent guide color, width ( `--indentation-guide-width`, `--indentation-guide-color`,  `--indentation-guide-color-active`)
- heading level padding (`--nav-item-padding`)

One example of another plugin doing this is the Git plugin since around this [update](https://github.com/denolehov/obsidian-git/blob/master/CHANGELOG.md#250-2022-09-28).

The differences between the default looks:
![image](https://user-images.githubusercontent.com/5298006/198268919-e5339a50-2cde-400c-9d7b-bb8419c5b119.png)

An example of a default outline styled with CSS variables:
![image](https://user-images.githubusercontent.com/5298006/198270488-64ac1454-49ee-4d51-9b1f-4fd3ee20d622.png)

**Comment by lerone-b** [comment]
yes, I would second this. the plugin is fabulous! but the two screaming colors (in relation to theme + overall look) make me resort to the core plugin... happy w/ any coffee-contribution for any extra efforts grateful in any way.

**Comment by guopenghui** [comment]
`0.3.14` supported color setting and changed some style, hope this will be helpful.

**Comment by NomarCub** [comment]
Hi!
The things that I listed are not done. What are the "some styles" that I can expect to be done? Should I open a new ticket for the others?

Here, the fold indent width and fold icon are still not consistent with the default theme and supported CSS variables.
![image](https://user-images.githubusercontent.com/5298006/209480536-a891e290-2adf-4324-96bf-34972626f5ea.png)

**Comment by NomarCub** [comment]
Hi!
I tried making every issue I have clear. Should I open a new ticket? Will this never be addressed?

**Comment by NomarCub** [comment]
For anyone still wondering, the new Obsisian version (1.2.7) has markdown rendering in the built in outline too.
