### ISSUE TITLE
支持无序列表内的标题

### ISSUE THREAD

**Issue by grisbear** [guopenghui/obsidian-quiet-outline#65]
\- # .....
    \- ## .....

**Comment by guopenghui** [comment]
这个比较困难。
貌似无序列表里面的标题不被obsidian认为是一个标题。比如你可以打开自带的大纲插件，里面也是不会显示列表里面的标题的。插件现在是直接用ob解析的结果，如果ob不解析这些标题，插件里面也很难做到这一点。

![image](https://user-images.githubusercontent.com/13451866/198867035-0de971c3-aac3-413a-ba73-a6b94fbde575.png)

quiet outline：
![image](https://user-images.githubusercontent.com/13451866/198867066-88e37f4e-6d32-4c4b-8520-2ce40c904597.png)

自带大纲：
![image](https://user-images.githubusercontent.com/13451866/198867077-d031c9cd-16fd-4f27-b7fb-3822217ec3c5.png)
