### ISSUE TITLE
[功能请求] 长标题显示不换行

### ISSUE THREAD

**Issue by domeniczz** [guopenghui/obsidian-quiet-outline#66]
过长的标题希望给个选项不换行，而是用 ... 省略无法显示的字

不然长标题一多，就很难看清了

真的希望有这个功能，谢谢!!!! 🥺

**Comment by guopenghui** [comment]
`0.3.4`中已支持，详情见https://github.com/guopenghui/obsidian-quiet-outline/releases/tag/0.3.4
