### ISSUE TITLE
[Problem] 點擊標題時，Obsidian window會有震動現象

### ISSUE THREAD

**Issue by emisjerry** [guopenghui/obsidian-quiet-outline#67]
在Quiet Outline panel點擊標題時，Obsidian window會有震動現象，核心的大綱面板則正常。

請檢視執行錄影(Default 佈景主題)：
https://youtu.be/gky2pO_j-8c

**Comment by emisjerry** [comment]
觀察後是編輯模式才有晃動現象。

**Comment by guopenghui** [comment]
你的电脑操作系统是什么？ 我是windows 10没有发生这个问题。

还有其他人有相同的问题吗？

**Comment by emisjerry** [comment]
Sorry, 逐一排查後發現是Table Enhancer plugin造成的。
只要搜尋到標題行的內容時就會晃動。
