### ISSUE TITLE
可否给层级切换器一组命令？

### ISSUE THREAD

**Issue by ShiTieSeng** [guopenghui/obsidian-quiet-outline#69]
从H1到H5各自的命令，这样就可以设置各自的快捷键盲操作，每次就不用手动点击了，手动点击还需要用眼睛去锁定鼠标需要点击的位置，不能形成肌肉记忆盲操作，效率还是有点慢。

**Comment by guopenghui** [comment]
切换层级后，不还是要用鼠标点击才能跳转吗，专门搞个键盘操作感觉对效率没太大改善

**Comment by ShiTieSeng** [comment]
切换后不跳转，主要就是目光扫一遍某一级的标题，回顾一下文章大概内容。一般需要跳转是用Quick Switcher++的Headings list mode trigger或Symbol list mode trigger，配合Advanced URI，可以实现系统级快捷键一键搜索标题
