### ISSUE TITLE
默认展开全部层次+调小子级标题字体大小

### ISSUE THREAD

**Issue by tyf2018** [guopenghui/obsidian-quiet-outline#7]
很好用的插件，谢谢作者。想反馈两个小细节： 

1. 能否默认展开全部层次？或者增加一个命令按钮以一键展开
2. 想调小子级标题字体大小（如下图所示），请问应该如何写css？谢谢
![image|100](https://user-images.githubusercontent.com/56342788/160729441-34de5fb5-d685-4a0d-bfc3-89cbf0644b7f.png)

**Comment by guopenghui** [comment]
1. 这个我试着放一个“默认展开到几级”的按钮或选择框，实现上应该不难，主要是还没想好这个按钮放到哪好看一些😂，重置按钮和搜索框那一行已经很挤了，另起一行又感觉按钮占的地方太大了。。
2. 现在的版本里面，不同级别的标题的元素在html里面是并列起来的没有嵌套关系，而且基本什么html属性都一样，所以没法区分。
后面我给不同级别的标题设置一个`level-[1-6]`的class，方便区分。这样就能分别设置样式了。

**Comment by tyf2018** [comment]
> 1.重置按钮和搜索框那一行已经很挤了

我觉得直接放在重置按钮的右边就行，两个按钮图标都可以做小一点

>    后面我给不同级别的标题设置一个 `level-[1-6]`的class

赞，字体调小后，除了便于区别，还能节省空间，个人觉得很有必要

**Comment by guopenghui** [comment]
上面的两个功能现在0.2.0版本已经支持了！
第1条可以看一下新的readme里面的`Level Switch Bar`功能
第2条我在`styles.css`里面专门留了这一条：
![image](https://user-images.githubusercontent.com/13451866/160888899-cbdacbbf-d69c-489c-ae03-7c20529ddab8.png)
直接改`font-size`就行

**Comment by guopenghui** [comment]
> 没有H6这个级别

因为H6是最低的级别，不会有子标题了，所有不会被展开。switch切换到h5的时候，已经展开全部标题了

> 切换到某些笔记时，H5标题仍然被折叠

这个可能后面改。昨天实现功能的时候，发现实现起来稍有些麻烦，也不太清楚使用场景，就暂时放弃了。
我有两个想法：
1. 在设置面板里面设置一个选项，用户自己输入想要的默认级别。然后后面切换笔记时都恢复到这个默认级别。
2. 切换的时候默认继承上一个笔记时设置的大纲级别
不知道这两种方案哪个符合你的使用习惯呢？


第2条在我这里测试是可以的🤔不太清楚原因
![image](https://user-images.githubusercontent.com/13451866/160961074-4b157d48-e32d-4251-b235-f5ed522d265d.png)
![image](https://user-images.githubusercontent.com/13451866/160961118-2bae9b5c-1802-4cfb-9117-126cb8f4d187.png)

**Comment by guopenghui** [comment]
`0.2.1`中已修正
