### ISSUE TITLE
大纲里点击不能跳转

### ISSUE THREAD

**Issue by GRELEEN** [guopenghui/obsidian-quiet-outline#71]
你好，在0.14.15版本时，点击大纲可以跳转至对应的地方，但是后续的新版obsidian及现在的1.03版，quietoutline0.3.6版点击大纲后毫无反应，均不能跳转至对应位置，导致我ob版本一直停留在0.14.15，因为对这个插件太依赖，希望您能看到我的问题

**Comment by GRELEEN** [comment]
现在恢复正常了，可以跳转

**Comment by guopenghui** [comment]
ob更新`0.15`版本的时候改了一些机制，后面的版本，插件都是按照新机制做的，不太确定在前面的ob版本还能不能正常工作。

但是`1.0.0`版本后应该是可以正常工作的，你是不是把插件面板拖到外部变成新窗口了？这种情况下确实是有问题，无法点击。

**Comment by GRELEEN** [comment]
> ob更新`0.15`版本的时候改了一些机制，后面的版本，插件都是按照新机制做的，不太确定在前面的ob版本还能不能正常工作。
> 
> 但是`1.0.0`版本后应该是可以正常工作的，你是不是把插件面板拖到外部变成新窗口了？这种情况下确实是有问题，无法点击。
短暂的故障，现在自己恢复了的，没有拖到外部，谢谢你的回复
