### ISSUE TITLE
[bug] 我在控制台总是能收到类似这样的报错

### ISSUE THREAD

**Issue by juestchaos** [guopenghui/obsidian-quiet-outline#73]
plugin:obsidian-quiet-outline:1003 Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
    at HTMLDocument.s (plugin:obsidian-quiet-outline:1003:2486)
    at s (app.js:1:692224)
    at l (app.js:1:692330)

s | @ | plugin:obsidian-quiet-outline:1003
-- | -- | --
  | s | @ | app.js:1
  | l | @ | app.js:1
  | setTimeout (async) |   |  
  | c | @ | app.js:1
  | scroll (async) |   |  
  | t.updateTabDisplay | @ | app.js:1
  | t.selectTabIndex | @ | app.js:1
  | (anonymous) | @ | app.js:1
  | s | @ | enhance.js:1

**Comment by guopenghui** [comment]
可以提供一下详细的复现步骤吗

**Comment by guopenghui** [comment]
如果仍有问题且可以稳定复现，可以重新打开issue
