### ISSUE TITLE
更新quiet_outline新版本后无法正常生效

### ISSUE THREAD

**Issue by Ordi-P** [guopenghui/obsidian-quiet-outline#76]
obsidian更新到最新版本1.0.3
quiet_outline最新版本0.3.11
更新过后quiet_outline完全无法工作，重启插件重启obsidian重装插件都没有作用

**Comment by guopenghui** [comment]
详细描述一下“无法工作”的具体情况？

**Comment by Ordi-P** [comment]
> 详细描述一下“无法工作”的具体情况？

老版本我是正常运行的，今天更新就出这问题了，具体老版本号不记得了。
奥对了，之前使用老版本有个小问题顺便说一下吧，就是如果两个连着的标题都是不止一行，这两个标题会有重叠和错位的情况。

**Comment by guopenghui** [comment]
第一个问题，插件本身是不会自动开启的，需要用命令打开。之前每次启动ob能打开是因为ob记录了上次关闭时的状态。
![image](https://user-images.githubusercontent.com/13451866/206912106-aa4441b6-a753-4e40-9e3c-33a7e29189bf.png)


第二个问题我这边没有复现出来：
![image](https://user-images.githubusercontent.com/13451866/206912047-2d09eb63-cd49-48b2-a2ef-d298e1a97bb9.png)

**Comment by Ordi-P** [comment]
> 第一个问题，插件的面板本身是不会自动开启的，需要用命令打开。之前每次启动ob能打开是因为ob记录了上次关闭时的状态。 ![image](https://user-images.githubusercontent.com/13451866/206912106-aa4441b6-a753-4e40-9e3c-33a7e29189bf.png)
> 
> 第二个问题我这边没有复现出来： ![image](https://user-images.githubusercontent.com/13451866/206912047-2d09eb63-cd49-48b2-a2ef-d298e1a97bb9.png)

好的感谢，确实是忘记要先执行这么个命令了，不过我觉得把这个功能做到第三方插件里面作为一个开关存在会不会更好呢？
第二个问题确实新版本修复了，是老版本有这个问题，抱歉。

不得不说这个插件确实是解决了obsidian一个虽然比较细节但是用户体验影响很大的问题，感谢您的插件的完善！
