### ISSUE TITLE
Reset button moves pane

### ISSUE THREAD

**Issue by NomarCub** [guopenghui/obsidian-quiet-outline#8]
I don't keep my outline in the upper right sidebar, so this makes the reset button unusable.

![reset](https://user-images.githubusercontent.com/5298006/160918899-ff2783e6-a52d-4578-aafc-633349ce8cda.gif)

**Comment by guopenghui** [comment]
You can temporarily use level switch instead. 
This `reset button` destroys the whole view and creates a new one,  which is an old implementation. I'll reconsider its function.

**Comment by guopenghui** [comment]
Fixed in `v0.2.1`
