### ISSUE TITLE
Cannot read properties of undefined (reading 'contains')

### ISSUE THREAD

**Issue by juestchaos** [guopenghui/obsidian-quiet-outline#80]
I have got a console error

Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
    at HTMLDocument.k (plugin:obsidian-quiet-outline:1003:4707)
    at s (app.js:1:702707)
    at l (app.js:1:702813)

This does not affect operation

**Comment by guopenghui** [comment]
Yes, I see this error too, but haven't find how to reproduce. I'll check on it.

**Comment by twherzog07** [comment]
I'm currently having an issue with Obsidian where the file cache regenerates each time it loads, so I was able to reproduce this bug consistently, so I submitted a pull request with a fix. Now I just need to figure out which file is causing my cache to regenerate each time, which should be fun..

**Comment by guopenghui** [comment]
The problem seems to be solved, if you still find problems, please reopen this issue.
