### ISSUE TITLE
当前查看的标题的一个bug

### ISSUE THREAD

**Issue by xingwumo** [guopenghui/obsidian-quiet-outline#81]
查看文档的时候，当我滑动文档，滑动到A标题时，大纲目录里，A标题会被加粗，表示用户在看A标题。
但是如果我点击大纲里的标题进行跳转，比如点击B标题，从A跳转到B标题。此时在滑动文档内容，滑动到C标题，大纲目录里，C标题不会被加粗，也就是说此说大纲目录不会表示当前用户所在的标题。

然后是我的一个个小小请求，在我用的某些主题里。在查看某个标题的时候，大纲目录会对这个标题进行加粗，来表示用户在看这个标题。但是只是文字加粗，有点不明显，如果能在大纲对正在看的标题进行更明显的标注就更好了（

**Comment by guopenghui** [comment]
跳转后再滑动，当前所在标题应该也会加粗的。这个功能是监听滑动事件来实现的，只要产生了滑动，就会刷新加粗的位置。 没有加粗可能是没有滑动到位置。

第二个可以自己设置CSS来实现，当前位置是用`.located`这个CSS类来标注的：
![image](https://user-images.githubusercontent.com/13451866/209470268-984d90c4-01d1-4126-a1e5-d8f94ecc7a85.png)

类似：
```css
.n-tree-node.located {
    /* 你想设置的样式 */
}
```

**Comment by xingwumo** [comment]
您好大佬。关于第一个问题，我试了一下，那个BUG还在，比如，我在大纲里，点击了第一个标题，
![image](https://user-images.githubusercontent.com/106624739/209482345-c4f349c0-91a9-48c6-bf93-a20bb2f4e551.png)，此时用鼠标滚轮向下滑动，无论滑动到哪里，都只有第一个标题是被选中的
![image](https://user-images.githubusercontent.com/106624739/209482358-c9753377-4ed3-4ece-97bb-1ab91137079b.png)
而此时，只有点击滑动条去滑动，大纲才会显示你的
![image](https://user-images.githubusercontent.com/106624739/209482369-0e6b149a-3acf-4664-a498-ccee2bff00d5.png)。不知道是不是我的Ob版本问题，我的Ob版本是0.15.9

**Comment by xingwumo** [comment]
很奇怪，点击大纲标题后，用鼠标滚轮滑动就会有这个BUG，但是拖动滑动条滑动就没有

**Comment by xingwumo** [comment]
> 跳转后再滑动，当前所在标题应该也会加粗的。这个功能是监听滑动事件来实现的，只要产生了滑动，就会刷新加粗的位置。 没有加粗可能是没有滑动到位置。
> 
> 第二个可以自己设置CSS来实现，当前位置是用`.located`这个CSS类来标注的： ![image](https://user-images.githubusercontent.com/13451866/209470268-984d90c4-01d1-4126-a1e5-d8f94ecc7a85.png)
> 
> 类似：
> 
> ```css
> .n-tree-node.located {
>     /* 你想设置的样式 */
> }
> ```
