### ISSUE TITLE
关于大纲选中标题的bug

### ISSUE THREAD

**Issue by xingwumo** [guopenghui/obsidian-quiet-outline#83]
您好作者大佬，关于之前我遇到的bug可能描述的不太清楚，我这里用截图描述一下。

比如，我在大纲里，点击了第一个标题。
![image](https://user-images.githubusercontent.com/106624739/209552346-5bc7c1d2-6040-485c-97ef-bdc50d239ab4.png)

此时用鼠标滚轮向下滑动（注意是用鼠标滚轮滑动），无论滑动到哪里，大纲目录都只显示刚刚点击的标题是被选中的。（哪怕滑动到其他标题也是如此）

![image](https://user-images.githubusercontent.com/106624739/209552054-5327703d-4ad8-4d0b-8658-b030b399ac65.png)

而此时，只有去拖动滑动条去滑动，大纲才会恢复正常显示
![image](https://user-images.githubusercontent.com/106624739/209552117-a2598c01-00e9-4868-98bb-a03a3e8b26a6.png)

这里不知道是不是是我的Ob版本问题，因为我的Ob版本是0.15.9

**Comment by guopenghui** [comment]
view没被选中的问题，之前ob一次更新让侧边栏也能获取焦点，焦点不在编辑区域，获取view失败了。

暂时的话你可以试试在点击跳转之后，再回来点击一下编辑区域，然后再滑鼠标滚轮，就没问题了。

这个问题我修复了，下次发版的时候更新。

**Comment by xingwumo** [comment]
OK,爱你么么哒

**Comment by guopenghui** [comment]
可以查看 `0.3.15` 看是否解决

**Comment by FlyingWhale2022** [comment]
好像还是没有解决这个bug

**Comment by guopenghui** [comment]
因为时间较久了，后面的更新修改了实现方案，且暂时没发现还有这个问题。所以把这个issue关闭。

如果还有问题，开一个新的issue来讨论。
