### ISSUE TITLE
Tags that are at the beginning of the headers are not rendered

### ISSUE THREAD

**Issue by bmv-2143** [guopenghui/obsidian-quiet-outline#85]
If a tag is located at the beginning of a heading it is not rendered (see screenshot). Tag in the middle and at the end of a heading are rendered fine.

P.S. Thank you very much for the wonderful plugin! It is awesome!

![obsidian-quite-outline-first-tag-in-the-heading-is-not-rendered](https://user-images.githubusercontent.com/4759923/210245798-05bfb360-b2b6-4529-baed-ad340f02f736.png)

**Comment by guopenghui** [comment]
fixed, will appear in next update.
<img src="https://user-images.githubusercontent.com/13451866/210254405-8eb4138e-006f-4f2d-8201-0d5b3ec32cf2.png" width="600">

**Comment by guopenghui** [comment]
supported in `0.3.15`

**Comment by guopenghui** [comment]
supported in `0.3.15`
