### ISSUE TITLE
Obsidian v1.1.9无法启动插件！

### ISSUE THREAD

**Issue by gxh1996** [guopenghui/obsidian-quiet-outline#86]
头疼，没法开启插件。

![image](https://user-images.githubusercontent.com/48506232/210596343-02c60f0b-266f-49af-84d1-66b36eb9c5c4.png)

![image](https://user-images.githubusercontent.com/48506232/210596511-5faa6d92-4f33-4999-8550-6d2bcad72971.png)

**Comment by guopenghui** [comment]
我这里也是`1.1.9`但是可以启动，安装版本 `1.0.3`。 不知道是新的安装版本的问题，还是其他问题。  你按Ctrl + Shift + i 打开控制台，看看有没有什么报错信息

**Comment by gxh1996** [comment]
> 我这里也是`1.1.9`但是可以启动，安装版本 `1.0.3`。 不知道是新的安装版本的问题，还是其他问题。 你按Ctrl + Shift + i 打开控制台，看看有没有什么报错信息

谢谢，解决了，没有main.js文件。我是在Obsidian上下的插件，不知道咋搞的没这个文件。于是在github上重新下载了下。

![Snipaste_2023-01-05_22-15-12](https://user-images.githubusercontent.com/48506232/210802291-d131934f-5c06-4aad-8d40-bf2730f5b902.png)

![Snipaste_2023-01-05_22-15-24](https://user-images.githubusercontent.com/48506232/210802307-0c0cf66f-99b6-432c-a3fc-57e33a621a86.png)
