### ISSUE TITLE
BUG反馈：部分关键词搜索导致的大纲失效

### ISSUE THREAD

**Issue by Lontern-520** [guopenghui/obsidian-quiet-outline#89]
大纲中输入"delete("，大纲自己就被干掉了！

**Comment by guopenghui** [comment]
开了正则模式没有？更新到最新版本了吗？我这里不会发生这个问题

非正则模式：
![image](https://user-images.githubusercontent.com/13451866/211777203-0c776013-baa7-41a3-a0a4-36970dc5f56c.png)

正则模式：
![image](https://user-images.githubusercontent.com/13451866/211777324-bd6c5395-254d-4489-bcf5-6183423b717f.png)

**Comment by Lontern-520** [comment]
是最新版本，非正则模式下的确不会出现这个问题，正则才会出现。

**Comment by guopenghui** [comment]
我想起来了，之前我发现这个问题然后修复了，但是后来一直没发布版本🤣。所以在我的测试库里测试没问题。

![image](https://user-images.githubusercontent.com/13451866/211863766-dd27809b-9d64-4178-8eca-bbc5e0a22d56.png)

明天我把这个更新发布一下

**Comment by guopenghui** [comment]
已修复
