### ISSUE TITLE
[Bug]: `Set Primary Color` option doesn't take effect

### ISSUE THREAD

**Issue by hustrjh** [guopenghui/obsidian-quiet-outline#91]
## My Problem
After enabling **`Primary Color`** and changing it to other color there's no effect in `Quiet Outline Pane`. **`Rainbow Line Color`** option takes effect though. Have I missed something?

![image](https://user-images.githubusercontent.com/69783980/213625461-94d066cb-9434-46eb-8987-55ca1265d3f0.png)

**Comment by guopenghui** [comment]
Not sure, this takes effect in my app. Is there any error or warning in dev console?

**Comment by hustrjh** [comment]
There's no error or warning in dev console. I've tested in sandbox vault.

Patch default color
![image](https://user-images.githubusercontent.com/69783980/213702496-424eb9ae-a446-46b2-8e60-d7e9601cb48b.png)

No effect in sandbox vault
![image](https://user-images.githubusercontent.com/69783980/213702612-fb5aad75-ad70-444f-bf1f-a98a2ffeb8ee.png)

**Comment by guopenghui** [comment]
Oh, I think color patching only affects the color of searching area and level switcher, but they seem to be hidden on your UI.

On my UI:

![image](https://user-images.githubusercontent.com/13451866/213733190-ba797616-5ce3-4b07-adde-4e4440ff3bb4.png)

![image](https://user-images.githubusercontent.com/13451866/213733363-ff83f4ab-0421-4216-872d-d8372d2aaa0a.png)

![image](https://user-images.githubusercontent.com/13451866/213733387-439f110a-f29b-430e-a5a1-727c8f4bad36.png)

**Comment by hustrjh** [comment]
I got it.

Thanks for your reply. So could I request such feature which highlighting current heading?

**Comment by guopenghui** [comment]
You can make another fr for that and close this issue.

**Comment by hustrjh** [comment]
OK, thank you!
