### ISSUE TITLE
quiet outline didn't work

### ISSUE THREAD

**Issue by daniel-0705** [guopenghui/obsidian-quiet-outline#94]
As below picture, the heading didn't work in outline, and the quiet outline icon didn't show, either.

My obsidian version is 1.1.9.

My plugin version is 0.3.14.

![截圖 2023-01-26 下午1 21 01](https://user-images.githubusercontent.com/51054109/214764081-7149f802-bd6e-4acb-9338-6091308f2198.png)

**Comment by guopenghui** [comment]
Open command panel and input `Quiet Outline` ，then press Enter .

**Comment by daniel-0705** [comment]
it works!!

Thank you!
