### ISSUE TITLE
疑问:在编辑模式如何自动展开标题？

### ISSUE THREAD

**Issue by ZekunC** [guopenghui/obsidian-quiet-outline#95]
现在的情况是，我输入了h1标题，接着输入h2标题，这个时候h1标题还是未展开的状态，不太跟手。如果可以的话，是否可以加一个选项设置，这个功能挺有用的。

**Comment by guopenghui** [comment]
目前来看这个功能短期不会实现，因为现在的刷新方案是在标题被改变时，获取所有标题，然后统一刷新。

所以无法得知哪个标题是刚刚添加的，因此也不会被标记为展开。要实现新标题默认展开的话，需要写算法来算diff，有些复杂。

**Comment by guopenghui** [comment]
如果后面有好的方案，我再重新打开这个issue。
