### ISSUE TITLE
高亮问题

### ISSUE THREAD

**Issue by Hope2KZ** [guopenghui/obsidian-quiet-outline#97]
文件当前位置在大纲中显示不明显（我用的是 dark 类的主题）
能否 实现高亮 颜色自定义等功能 能够让用户设置颜色亮度等
嵌入插件 或者 支持Style Settings

**Comment by guopenghui** [comment]
直接换成另一种颜色好像就能解决问题，我试试把当前位置字体颜色换成插件的主颜色

**Comment by Hope2KZ** [comment]
> 直接更换成另一种颜色好像就能解决问题，我试试把当前位置字体颜色更换成插件的主题色

已经实现 非常感谢 加油

**Comment by vanbang9710** [comment]
> > Directly changing to another color
Could you please elaborate further? I also have this problem.

**Comment by Hope2KZ** [comment]
> > > Directly changing to another color
> 
> Could you please elaborate further? I also have this problem.

The color of the directory's current location is equal to the main color of obsidian software
（ settings -> appearance -> subject color ）
